.storybook/ThemeContainer.js, .storybook/ThemeSwitcher.js, .storybook/components/CardStory.js, components/Pagination.js, components/Tag.js, internal/ClickListener.js
I found a few calls to `React.PropTypes` hanging around; this fixes ’em.
=> fix(PropTypes): remove deprecated calls to React.PropTypes

.storybook/components/InteriorLeftNavStory.js, components/InteriorLeftNavItem.js, components/__tests__/InteriorLeftNavItem-test.js
Issue raised in Slack:
This PR goes back to [the previous way this component accepted single children nodes](https://github.com/carbon-design-system/carbon-components-react/blob/7e195d77fe79109a86ef2d61f1c4ab08bb9de5a6/components/InteriorLeftNavItem.js#L46).
=> fix(InteriorLeftNavItem): revert back to accepting single children

.storybook/components/CardStory.js, components/ToolbarSearch.js
Use the PropTypes modules instead of using the deprecated
React.PropTypes method
=> fix: use propTypes from module instead of React

components/InteriorLeftNav.js, yarn.lock
Currently InteriorLeftNav wipes out initial state on `componentDidMount` - reset to let the initial state declaration accept `window.location.pathname` if nothing else is passed in
=> fix(activeHref): set active href in constructor, not mount

.storybook/components/PaginationStory.js, components/Pagination.js
Add prop that allows a user to pass `isLastPage` that disables the forward arrow
=> fix(pagination): disable button on last page

components/Toolbar.js, components/Tooltip.js, components/TooltipSimple.js
Few more places PropTypes were being used from React instead of their
own module
=> fix(propTypes): fix more deprecated Proptype usage

components/__tests__/DetailPageHeader-test.js
The DetailPageHeader test was:
- missing descriptions for Icons
- missing a title for DetailPageHeader
- had in invalid prop `isLastItem` for OverflowMenu
=> test(detail-page-header): test fix for props

components/OverflowMenu.js, components/__tests__/OverflowMenu-test.js
Simpler version of https://github.ibm.com/Bluemix/bluemix-components-react/pull/505 to get OverflowMenu operational in IE11 again. Same issue as before 
> evt.relatedTarget was used in the handleBlur function, confusing IE11 (which does not have evt.relatedTarget on blur events).
=> fix(overflowmenu): remove handleBlur for now

components/TableBody.js
- Only stripe `TableRow` components (see carbon-design-system/carbon-components#207 in `carbon-components` for corresponding style fix)
- Don’t override user-set `even` prop values for striping
re #66
=> feat(TableBody): allow user override for striping

package.json
=> chore(tooling): manually pin storybook dependency at older version

components/Search.js, components/__tests__/Search-test.js
- use the input directly instead of storing value as state
- fix `defaultValue` prop
This should fix #56 and #30
=> fix(Search): defaultValue prop support

__tests__/index-test.js, package.json
An incorrect path in the index.js file would cause the library to fail
to import. This does a basic sanity check for that
=> test: add a basic test for index exports

.storybook/components/ToolbarStory.js, yarn.lock
Toolbar was throwing an error when running storybook (due to new export syntax), this fixes that.
=> fix(toolbar): fix import path in storybook

components/OverflowMenu.js, components/Tooltip.js, package.json, setup-jest.js
Several components launching floating menu have [forced synchronous layout](https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid_forced_synchronous_layouts), as shown below (notice purple bar as part of JavaScript stack, which should *not* happen). This PR attempts to fix such problem, allowing browser to layout in batch.
=> perf(floating-menu): reduce forced synchronous layout

components/OverflowMenu.js
React.Children.map errors out on conditional children - use React.Children.toArray to make sure to filter out any null values before mapping over the Array
=> fix(overflow): use React.Children.toArray to discard null values

.storybook/components/SearchStory.js, components/Search.js
Couple of bugs with the search
1) The clear icon was showing all the time, instead of only with content
2) The clear icon did not work when controlling the value of Search
This resolves both of those issues
=> fix(search): toggle the clear icon correctly and enable use on controlled components

components/OverflowMenuItem.js
A recent change used the React PropTypes property instead of the React one.
Fixes #99
=> fix(OverflowMenuItem): use PropTypes module

index.js
Changed the export of `StructuredList` to mimic its _structure_ 
Other changes in `index.js` are `prettier` formatting fixes.
=> fix(structured-list): change exported files

components/DetailPageHeader.js, components/__tests__/DetailPageHeader-test.js, package.json
Fixed the bug, added a test.
The test is in it's own `describe()` wrapper to localize the before/after hooks. Not absolutely required, but seemed like a good idea.
I also added [sinon](http://sinonjs.org/) as a dev dependency to make stubbing global methods a bit easier and less error-prone.
Fixes #94
=> fix(DetailPageHeader): Correctly remove scroll event listener

.storybook/components/PaginationStory.js, components/Pagination.js, components/__tests__/Pagination-test.js
Supports pagination with unknown total number of items:
- `pagesUnknown` indicates total is unknown
- `isLastPage` indicates last page when total is unknown
- `pageInputDisabled` hides the text input for jumping to a certain page
=> feat(pagination): supports pagination with unknown totals

components/Notification.js
related to #107 
This component will need a refactor since `Notification` relies on the `caption` prop to render either Toast or Inline notifications. This isn't possible as we need to give caption a `defaultProp` forcing the `caption` prop to always resolve as `true`....basically, this was some bad logic that I did when I originally wrote this and should be refactored in another PR.
=> fix(Notification): add string props to defaultProps (il8n)

components/OverflowMenu.js
Wrapping around to make sure this.menuEl isn't used before this.menuEl is actually defined
=> fix(overflow): only use menuEl if it exists

components/OverflowMenu.js
Opening this to let people test against this, to see if this resolves the null issue. I haven't been able to isolate an appropriate test case to reproduce the bug though
=> fix(overflow): wrap ref usage in if statement anyways

package.json, server-side-rendering-tests/loads.js
Adds a workaround for the flatpickr SSR bug and a basic SSR smoke test to ensure the lib can be at least loaded in a server-side context.
The workaround and the test are both a little barren, but I believe they're both good enough, and a solid improvement over the previous situation. The test has to live outside of jest because jest will pollyfill `window` and make things work in jest that  throw errors in Node.js.
It wouldn't be a bad idea to add an additional test that renders everything in `.storybook/components/` in Node.js to get a little more thorough coverage.
Fixes #76
=> fix(DatePicker): fix server-side-rendering (#76)

components/DatePicker.js, components/Tabs.js, internal/FloatingMenu.js, package.json
As the newly introduced eslint-plugin-react rule says, most of use cases of `findDOMNode()` have better alternatives, like what this change does.
Fixes #170.
=> chore(components): go away from findDOMNode()

.storybook/components/PaginationStory.js, components/Pagination.js
Resolves: https://github.com/carbon-design-system/carbon-components-react/issues/125
I'm now generation a random ID for each component on `componentWillMount` and move `id` to a prop - server side rendering UI's will need to pass in `id`'s manually
=> fix(pagination): add id as prop and change unique creation

components/Pagination.js
Reverting an accidental change to how the id was being used.
Adding the change from 7ea8ab9 back in that was taken out in
241a15e
Fixes #200
=> fix(Pagination): use id as prop again

.storybook/components/SliderStory.js, components/Slider.js, components/__tests__/Slider-test.js
Closes #204 
Fixes the following problems in the Slider component:
- Execute `this.props.onChange()` when the Slider value changes.
- Corrects `setState()` usage. [More info](https://facebook.github.io/react/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous)
- Remove use of arrow functions in JSX props. [More info](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md)
- Use `PureComponent` to automatically bind class functions.
=> fix(slider): onChange not being called, resolves #204

.storybook/components/DropdownStory.js, components/Dropdown.js, components/__tests__/Dropdown-test.js, package.json
closes #119 
Allows a `disabled` prop to be added to the component.
A new 'disabled' story for the dropdown component.
N/A
The `disabled` prop adds a class of `bx--dropdown--disabled` to trigger a visual change, and prevents the `toggle` custom method from changing the state.
Added appropriate tests to existing file.
=> feat(Dropdown): add disabled state

components/ModalWrapper.js
The `handleSubmit` prop of the `ModalWrapper` made it's way through the `other` object to `Modal`, which in turn placed that prop on a plain `<div>` and caused an error.
I removed `handleSubmit` from `other` and kept the assignment to `onRequestSubmit`
Fixes #216
=> ModalWrapper handleSubmit fix

.storybook/components/LinkStory.js, .storybook/components/OrderSummaryStory.js, components/OrderSummary.js, components/__tests__/OrderSummaryFooter-test.js, yarn.lock
- Set `target="_blank"` as default for `OrderSummaryFooter`
=> fix(order-summary): open order summary links in new window by default

.storybook/components/OrderSummaryStory.js, components/Dropdown.js
Adding `selectedText` to the Dropdown gave a warning about `Unknown prop selectedText on <ul> tag`. So I added `selectedText` to the props list, so it's not added in with the `...other` object on the ul.
=> fix(dropdown): added selectedText prop to the list to avoid warning

components/FileUploader.js, components/__tests__/FileUploader-test.js
closes #235 
Adds an optional `buttonKind` prop to the `FileUploader` component that allows you to override the default primary button style to be secondary. 
Ready for review
=> feat(FileUploader): allow setting button style via prop

components/Slider.js
If there is a min value different than 0 then it has a bug on pointing the slider thumb in wrong place. 
This is a fix for this issue.
=> fix(Slider): Fixing for custom min / max values

components/NumberInput.js
Resolves #245
Fixes the sizing of the control buttons for number input. The icons weren't being wrapped in a button component as expected by `carbon design`, so they're currently [really tiny](http://react.carbondesignsystem.com/?selectedKind=NumberInput&selectedStory=enabled&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel):
=> fix(number-input): control buttons

components/InteriorLeftNav.js
`onClick` requires a function, but was sometimes getting `false`. This follows the same pattern, but returns a no-op instead of false to avoid a warning.
I'm sending this up because I'm _pretty sure_ it's the right move. I tested locally and the nav opens and closes as expected without any console errors. Probably worth taking a look to ensure this doesn't introduce any weird regressions.
close #252
=> fix(InteriorLeftNav): always pass a function

components/Dropdown.js, components/__tests__/Dropdown-test.js
Closes carbon-design-system/carbon-components-react#29
Bugfix PR for #29, didn't know if we wanted to support this officially but figured I'd PR it to start the discussion 😄 
**New**
**Changed**
- `Dropdown`
- `children` in Dropdown are now cloned with an `onClick` handler that invokes the child's `onClick` prop (if it exists) and then calls `handleItemClick`.
- `Dropdown-test`
- Added a simple test to verify the above behavior
**Removed**
=> fix(Dropdown): call onClick for items if one exists

components/CodeSnippet.js, components/__tests__/CodeSnippet-test.js
Closes carbon-design-system/carbon-components-react#55
Updates `CodeSnippet` to include a new prop, `wrappedContentRef`, that allows access to the `<pre>` element in the component (making it easier to copy!).
**New**
**Changed**
- `CodeSnippet`
- Added `wrappedContentRef` as a new prop
- `CodeSnippet-test`
- Added test to assert ref is called and passes the correct node
**Removed**
=> feat(CodeSnippet): add wrappedContentRef to access <pre> contents

components/TableData.js, components/__tests__/TableData-test.js
Allows the icon to toggle with enter and space keys, not just click
Fixes #244
=> fix(TableData): add a11y for expand toggle

package.json, yarn.lock
Updates `carbon-components` dependency to `^8.0.0`. 
**Note**: This commit is flagged as a `BREAKING CHANGE`
**New**
**Changed**
- `package.json`
- `yarn.lock`
**Removed**
=> feat: update carbon-components to v8

components/Checkbox.js
e.g. the checkbox labelText is limited to be used with the string proptypes, so there will be warnings when passing in a number, or a valid component. 
As no modifications happen on the props and this is only something that gets rendered down the line, why limit its use? Use the proptype.node instead of proptype.string, proptype.number to allow anything that can be rendered to be passed in.
Everywhere in the code where props are simply being rendered without being modified, change the proptype from e.g. proptype.string, proptype.number to proptype.node
=> feat(checkbox): allow more props to be rendered when not modified

package.json
Closes carbon-design-system/carbon-components-react#320
**New**
**Changed**
- `"engines"` field removed from `package.json`
**Removed**
=> chore: remove engines field

src/components/Slider/Slider.js
Sets the default input type of the slider to `number`
Closes https://github.com/carbon-design-system/carbon-components-react/issues/278
=> fix(slider): set default input type to number

src/components/DatePicker/DatePicker-test.js, src/components/DatePicker/DatePicker.js
Closes carbon-design-system/carbon-components-react#350
Added a new prop 'value' in DatePicker Component and the code to handle the date change to set the value programmatically.
Change log
Changed:
Added new Prop value, to set the value programmatically
Updated tests
=> Added a new prop to set the date value programmatically, resolves #350

src/components/ComposedModal/ComposedModal.js
Closes carbon-design-system/carbon-components-react#354
Fixed react warning `Unknown prop `closeModal` on <div> tag` in the `ComposedModal` component
**New**
- Added `closeModal` to `propTypes` and the render method of `ModalFooter`
=> fix: react warning in ComposedModal component, resolves #354

src/components/Modal/Modal-test.js, src/components/ModalWrapper/ModalWrapper.js
Closes carbon-design-system/carbon-components-react#342
Allow product teams to pass in a prop to set kind for modalWrapper's trigger button 
**New**
- pass props through modalWrapper to set kind for the trigger button
- default to primary button if no props passed
=> feat(ModalWrapper): set kind for trigger button (#342)

src/components/Form/Form-story.js
The current story tries to submit the form for real making the page change. This prevents this and shows an item in the action panel instead
=> fix(Form): do not submit story for real

src/components/NumberInput/NumberInput.js
Closes carbon-design-system/carbon-components-react#361
pass onClick and OnChange as a callback to setState to ensure they are not called before state.value is updated. This will keep any parent component that accesses this.state.value via refs during onChange synchronized with the value displayed in the input field.
**Changed**
- don't call onClick or onChange until this.state.value is changed.
=> fix(NumberInput): call onClick, onChange after setState

package.json, yarn.lock
Closes carbon-design-system/carbon-components-react#378
Removed `react-addons-css-transition-group` from dependencies as it was no longer being used and causing warnings with React 16.
- Removed `react-addons-css-transition-group` from `package.json` and updated the `yarn.lock` file. I doesn't look like the `yarn.lock` file was updated via https://github.com/carbon-design-system/carbon-components-react/pull/366.
=> fix: remove unused dependency react-addons-css-transition-group, resolves #378

package.json, src/components/InteriorLeftNav/InteriorLeftNav-story.js, src/components/InteriorLeftNav/InteriorLeftNav-test.js, src/components/InteriorLeftNav/InteriorLeftNav.js, src/components/InteriorLeftNavItem/InteriorLeftNavItem-test.js, src/components/InteriorLeftNavList/InteriorLeftNavList-test.js, src/components/InteriorLeftNavList/InteriorLeftNavList.js, yarn.lock
Updates `eslint-plugin-jsx-a11y` to `v6`
- Changed empty `href` to actual links
- Changed `left-nav-list__item-link` from `a` to `div` since it was not being used to navigate
=> fix(a11y): update jsx-a11y to v6

src/components/NumberInput/NumberInput-test.js, src/components/NumberInput/NumberInput.js
- Add button type to arrow button to prevent a form from being submitted
when it is clicked
- Disable the arrow buttons when the NumberInput is disabled just in
case
Fixes #358
=> fix(NumberInput): add button type and disabled

src/components/AccordionItem/AccordionItem.js
By default, `<button>` in a form will submit the form if it's interacted with. Adding `type="button"` here will cause this not to be the default behavior.
**New**
**Changed**
- `<AccordionItem>`
**Removed**
=> fix(AccordionItem): add explicit `type` attribute

src/components/Tooltip/Tooltip-story.js, src/components/Tooltip/Tooltip-test.js, src/components/Tooltip/Tooltip.js, src/internal/FloatingMenu.js
This PR is an update to @tw15egan 's very good [#392](https://github.com/carbon-design-system/carbon-components-react/pull/392).
- Changes direction proptypes to PropTypes.oneOf(['bottom', 'top', 'left', 'right'])
- Adds in menuOffset prop (optional) to ensure Tooltip is always positioned correctly. Usage is as follows:
```
<Tooltip triggerText="Hover Info Here">
```
or
```
<Tooltip triggerText="Hover Info Here" menuOffset={{left: 10, top: 30}}>
```
Replaces PR [#392](https://github.com/carbon-design-system/carbon-components-react/pull/392)
Fixes Issue [#390](https://github.com/carbon-design-system/carbon-components-react/issues/390).
=> Tooltip: Add Even Better Positioning!

src/components/Tooltip/Tooltip.js
Closes carbon-design-system/carbon-components-react#384
**New**
**Changed**
- `Tooltip`
- Added check to `getTriggerPosition` to make sure `ref` is non-`null`
**Removed**
=> fix: add guard to triggerEl ref

src/components/NumberInput/NumberInput-test.js, src/components/NumberInput/NumberInput.js
onChange and onClick will now receive the events used to trigger them.
This is a regression fix.
They will also receive the direction as a second argument if the arrows
are used.
Fixes the tests as they were returning false positives when checking on
spies. The spies were not reset between test runs so passing it in one
test means it passed in the rest.
Fixes #369
=> fix(NumberInput): pass the evt and dir to events

package.json, src/components/NumberInput/NumberInput-story.js, src/components/NumberInput/NumberInput-test.js, src/components/NumberInput/NumberInput.js, yarn.lock
Add support for the invalid flag and for invalidText
Fixes #373 
Blocked by Carbon core not properly supporting invalidText with NumberInput (styles are wrong)
=> feat(NumberInput): add invalidText and invalid

src/internal/FloatingMenu.js
Closes #410 
Details are in the issue, but there's an easier way to test. 
1. In Tooltip.js add `<h1>XXX</h1>` at the beginning and end of the render method, just inside the enclosing `<div>`, so that you have enough content to scroll. About 15 at the beginning and end should be enough. 
2. Open existing Storybook with `npm run storybook`
3. Click [this link](http://localhost:9000/?selectedKind=Tooltip&selectedStory=position%20-%20right&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) in your local environment to go directly to **_Tooltip: Position Right_** 
- Note: Left and Bottom are not broken! Test with the **_right_** side!
4. hover over tooltip, everything is okay
5. Scroll down a smidge, just a little, and hover again. Tooltip is too high.
6. Scroll …
=> fix(FloatingMenu): remove parens

src/components/Form/Form-story.js, src/components/TextArea/TextArea-test.js, src/components/TextArea/TextArea.js, src/components/TextArea/Textarea-story.js
The export for TextArea was set to camelcase. Other places used all
lower case, specifically the stories. If the story was copy and pasted,
the resulting code was wrong
=> fix(TextArea): match casing everywhere

src/components/Module/index.js
Fixes #423.
Removed the re-exporting line of the default export in `Module/index.js`, since it does not exist actually.
=> fix(Module): fix wrong re-export in Module/index.js

src/components/TextInput/TextInput.js
Closes carbon-design-system/carbon-components-react#424
Adds `aria-invalid` to invalid textInput and `aria-describedBy` to the error message associated with the text field.
=> fix(textInput): Add aria-invalid and aria-describedBy to invalid textInput

src/components/Modal/Modal-test.js, src/components/ModalWrapper/ModalWrapper.js
Closes #356
Updates prop to follow camelCase naming convention.
**New**
**Changed**
- `ModalWrapper`
- `triggerButtonkind` -> `triggerButtonKind`
**Removed**
=> fix(ModalWrapper): update trigger prop to follow camelCase

src/internal/ClickListener.js, src/internal/InnerClickListener.js, src/internal/__tests__/ClickListener-test.js, src/internal/__tests__/InnerClickListener-test.js, src/internal/__tests__/__snapshots__/ClickListener-test.js.snap, src/internal/__tests__/__snapshots__/InnerClickListener-test.js.snap
Closes #425, Closes #344
Update `ClickListener` and introduce `InnerClickListener`.
**New**
- `InnerClickListener`
- Adds ability to listen to nodes inside of a component rather than the top-level node
**Changed**
- `ClickListener`
- removes wrapping `div` node and adds ref directly to child component
**Removed**
=> Update `ClickListener` and introduce `InnerClickListener`

src/components/ListBox/ListBox.js, src/components/ListBox/ListBoxField.js, src/components/ListBox/ListBoxMenu.js, src/components/ListBox/ListBoxMenuIcon.js, src/components/ListBox/ListBoxMenuItem.js, src/components/ListBox/ListBoxPropTypes.js, src/components/ListBox/ListBoxSelection.js, src/components/ListBox/README.md, src/components/ListBox/__tests__/ListBox-test.js, src/components/ListBox/__tests__/ListBoxField-test.js, src/components/ListBox/__tests__/ListBoxMenu-test.js, src/components/ListBox/__tests__/ListBoxMenuIcon-test.js, src/components/ListBox/__tests__/ListBoxMenuItem-test.js, src/components/ListBox/__tests__/ListBoxSelection-test.js, src/components/ListBox/__tests__/__snapshots__/ListBox-test.js.snap, src/components/ListBox/__tests__/__snapshots__/ListBoxField-test.js.snap, src/components/ListBox/__tests__/__snapshots__/ListBoxMenu-test.js.snap, src/components/ListBox/__tests__/__snapshots__/ListBoxMenuIcon-test.js.snap, src/components/ListBox/__tests__/__snapshots__/ListBoxMenuItem-test.js.snap, src/components/ListBox/__tests__/__snapshots__/ListBoxSelection-test.js.snap, src/components/ListBox/index.js, src/prop-types/__tests__/childrenOf-test.js, src/prop-types/__tests__/childrenOfType-test.js, src/prop-types/childrenOf.js, src/prop-types/childrenOfType.js, src/prop-types/tools/__tests__/getDisplayName-test.js, src/prop-types/tools/createChainableTypeChecker.js, src/prop-types/tools/getDisplayName.js
Extracted `ListBox` and other relevant bits from #332 for a simpler diff.
**New**
- `ListBox`: see [`README.md`](https://github.com/carbon-design-system/carbon-components-react/pull/435/files#diff-8d1d10a4d2221059c29d4000987f7dfb)
- `prop-types`
- `childrenOf` `prop` validator for children of a given set of types
- `childrenOfType` `prop` validator for children of a singletype
- `tools`
- `createChainableTypeChecker`: chaining required for supporting `isRequired`
- `getDisplayName`: get name for a given React element or component
**Changed**
**Removed**
=> Add `ListBox` component

package.json, src/components/ListBox/ListBoxField.js, src/components/ListBox/test-helpers.js, src/components/MultiSelect/MultiSelect-story.js, src/components/MultiSelect/MultiSelect-test.js, src/components/MultiSelect/MultiSelect.js, src/components/MultiSelect/index.js, src/internal/Selection.js, src/internal/__tests__/Selection-test.js, src/internal/__tests__/__snapshots__/Selection-test.js.snap, src/prop-types/childrenOf.js, yarn.lock
Adds MultiSelect to the project
**New**
- `internal/Selection` for handling selections across dropdowns
- `components/MultiSelect/*` for MultiSelect
**Changed**
- Update `package.json` to bring in newer `carbon-components` and `downshift`
- `childrenOf` `prop-type` should ignore no children.
**Removed**
=> feat(components): add MultiSelect component

package.json
Add `version` field for new `semantic-release` dependency. In order to publish, it needs the version field apparently 😅 
**New**
**Changed**
- `package.json` now has a `version` field 
**Removed**
=> chore: add valid version field for semantic release

package.json, src/components/InteriorLeftNav/InteriorLeftNav-story.js, src/components/InteriorLeftNav/InteriorLeftNav-test.js, src/components/InteriorLeftNavItem/InteriorLeftNavItem-test.js, src/components/InteriorLeftNavItem/InteriorLeftNavItem.js, yarn.lock
Closes https://github.com/carbon-design-system/carbon-components-react/issues/169
Refactored `InteriorLeftNavItem` to have more customizable children and to accept both normal links and react-router links.
**Changed**
- The parent does not handle the `href` anymore
- The child can be either an anchor link or a react-router Link
=> fix(interior-left-nav): refactored so it accepts react router links

src/components/OverflowMenu/OverflowMenu-test.js, src/components/OverflowMenu/OverflowMenu.js
Fixes #433.
**New**
Code to recalculate the position of the trigger button, upon opening overflow menu.
=> fix(OverflowMenu): reposition menu upon change in open state

src/components/OverflowMenu/OverflowMenu-test.js, src/components/OverflowMenu/OverflowMenu.js, src/components/Toolbar/Toolbar-test.js
Fixes #420. Wanted to see if this kind of change makes sense.
**Changed**
With this change, the DOM for overflow menu is not rendered until it's open.
=> fix(OverflowMenu): clobber DOM for closed overflow menu

src/components/FileUploader/FileUploader-test.js, src/components/FileUploader/FileUploader.js
Fixes #431.
**Changed**
Use `bx--visually-hidden` CSS class instead of `hidden` attribute for the pseudo `<input>`.
=> fix(FileUploader): use an alternate way to hide pseudo <input>

package.json
The jest configuration is wrong: 'yarn test --coverage' reports the coverage as 'Unknown'. This PR fixes that to report the appropriate coverage figures to the 'coverage' folder.
=> Fix 'yarn test --coverage'

src/components/Breadcrumb/Breadcrumb-story.js, src/components/BreadcrumbItem/BreadcrumbItem.js, yarn.lock
Closes #279 
Refactored BreadcrumbItem to accept `react-router` links without showing a warning. 
**Changed**
- `BreadcrumbItem`
=> fix(breadcrumb): refactored so it accepts react router links

src/components/ComposedModal/ComposedModal.js
Closes carbon-design-system/carbon-components-react#440
Fixed issue where `ModalFooter` wasn't triggering onRequestSubmit when primary button is clicked
**Changed**
- Updated `ModalFooter` to call `onRequestSubmit` prop since there's no local method `this.onRequestSubmit`
=> fix: onRequestSubmit not triggering in ComposedModal component

src/components/DatePicker/DatePicker.js
Closes #402 
Fixed DatePicker so when the inputs are cleared, the calendar gets reset.
**Changed**
- `DatePicker.js`
=> fix(date-picker): reset calendar when inputs are cleared

package.json, yarn.lock
Prettier changes DatePicker.js upon pre-commit hook. This change is for prevent that from happening.
=> chore(Prettier): Upgrade Prettier

src/components/OrderSummary/OrderSummary.js
Resolves #513.
Added aria-labelledby to OrderSummary* components, tests shown to fail in issue #513 are now passing.
=> fix(OrderSummary): Add aria-labelledby, missing attributes fail A11Y tests

src/components/Tooltip/Tooltip-test.js, src/components/Tooltip/Tooltip.js, src/internal/FloatingMenu.js
Resolves #492.
This change also does:
* More strict type checks for `props` of geometries as well as `triggerText`.
* Avoids React "unknown DOM prop" warning for `clickToOpen`.
**New**
- `triggerClassName` prop in `<Tooltip>`
=> feat(Tooltip): allow custom CSS class for the trigger UI

src/components/Toggle/Toggle-test.js, src/components/Toggle/Toggle.js
Resolves #510.
**New**
- `onChange` prop to `Toggle` - It works as if the handler attached directly to `<input>`.
=> feat(Toggle): support onChange event

src/components/OrderSummary/OrderSummary.js
**Changed**
- Caching auto-generated element ID to component instance to avoid re-rendering (by changing ID with every render call).
=> chore(OrderSummary): avoid redundant rendering upon auto-generating element IDs

src/components/Slider/Slider-test.js, src/components/Slider/Slider.js
Resolves #234.
**New**
- `formatLabel` prop for `Slider`, which takes `min`/`minLabel` or `max`/`maxLabel` prop values and returns the formatted label string for min/max.
=> feat(Slider): support for custom value label formatting

src/components/Dropdown/Dropdown-test.js, src/components/Dropdown/Dropdown.js
If the `Dropdown` is given `null` children, it breaks on rendering. You can see this behavior by editing the `story` for `Dropdown`:
```javascript
.addWithInfo(
'with default text',
`
The Dropdown component is used for navigating or filtering existing content.
Create Dropdown Item components for each option in the dropdown menu.
`,
() => (
<Dropdown
{...dropdownEvents}
onChange={action('onChange')}
defaultText="Dropdown label">
<DropdownItem itemText="Option 1" value="option1" />
<DropdownItem itemText="Option 2" value="option2" />
{null}
<DropdownItem itemText="Option 3" value="option3" />
<DropdownItem itemText="Option 4" value="option4" />
<DropdownItem itemText="Option 5" value="option5" />
</Dropdown>
)
)
```
Results in this error:
The `React.Children` methods don't verify whether …
=> Fix(dropdown): handle null children

src/components/CardContent/CardContent-test.js, src/components/CardContent/CardContent.js
Resolves #515.
**New**
- `cardIcon` prop in `CardContent` now supports `PropTypes.node` - A custom icon (instead of `carbon-icons` sprite) in such case.
=> feat(Card): support custom icon

.storybook/.babelrc, config/jest/jsTransform.js, package.json, scripts/build.js, scripts/env.js, src/components/OverflowMenuItem/OverflowMenuItem.js, yarn.lock
Closes carbon-design-system/carbon-components-react#375
Updates build process and related tooling to use new Babel v7 packages. This has the added advantage of adding PURE notations to our components to help with tree shacking and DCE 😄 
**New**
**Changed**
- Update config to reference new Babel v7 packages
**Removed**
=> feat(build): update to babel v7

src/components/Dropdown/Dropdown.js
The role presentation attached to dropdown isn't considered a form element. Therefore when partnered with a <label> we get an accessibility error:
```
The id "identifier" referenced by the 'for' attribute of a label element is not a valid form input element or an element with id "identifier" is either null or does not exist.
```
Changing the role to Listbox makes the dropdown act as if it is a select. However each child will need to also have the role option so screen readers know which children are selectable. See #545
References:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_listbox_role
https://www.w3.org/TR/wai-aria/roles#listbox
=> Update Dropdown Role to Listbox

src/components/DropdownItem/DropdownItem.js
The role menuitem attached to DropDownItem is usually used as a child under [menu or menubar](https://www.w3.org/TR/wai-aria/roles#menuitem).
With the change to the role to listbox, #544 , the children will need to have the role option.
References:
https://www.w3.org/TR/wai-aria/roles#option
=> Update DropDownItem role to option

src/components/InteriorLeftNav/InteriorLeftNav-test.js, src/components/InteriorLeftNav/InteriorLeftNav.js
Fixes #534.
**New**
- Support for arbitrary types of child nodes under `<InteriorLeftNav>`.
=> fix(InteriorLeftNav): allow arbitraty child node types

src/components/Search/Search.js
Fixes #530.
**New**
- Support for arbitrary React nodes for `labelText` property in `<Search>`.
=> fix(Search): allow arbitrary React nodes for label

src/components/Tile/Tile.js
Remove `role="presentation"` from `label` element for a11y reasons. Closes https://github.com/carbon-design-system/carbon-components-react/issues/539
=> fix(a11y): remove role from label

.storybook/Container.js, .storybook/polyfills.js, README.md
Refs #533.
**New**
- `.storybook/polyfills.js`, which let you run Storybook on IE11 as well as works as the list of required polyfills.
=> chore(devenv): load polyfill into Storybook env

src/components/DataTable/DataTable-story.js, src/components/DataTable/DataTable.js, src/components/Search/Search.js
Also made a change to `<Search>` to make `id` prop fully optional.
Fixes #552.
**New**
- ID auto-gen feature for `<Search>`
**Removed**
- Hard-coded ID in `<DataTableSearch>`
=> fix(DataTable): remove hard-coded ID for <Search>

src/components/Icon/Icon.js, src/components/ListBox/__tests__/__snapshots__/ListBoxField-test.js.snap, src/components/ListBox/__tests__/__snapshots__/ListBoxSelection-test.js.snap, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
Although I disagree with this one because the title element is used by screen readers as the descriptor of svg's according to w3
```In order for elements with a role of img be perceivable, authors MUST provide alternative text or a label determined by the accessible name calculation.```
https://www.w3.org/TR/wai-aria/roles#img
=> All images, or role=img, including SVGs need to have an alt tag

src/components/DataTable/DataTable-story.js
This will ensure anyone who uses the `DataTable` story will use the correct `Button` type. Closes https://github.com/carbon-design-system/carbon-components-react/issues/554
=> fix(story): make sure DataTable is using small primary button

.gitignore, package.json, scripts/build.js, scripts/rollup.config.js
This change supports UMD in the build in our `lib` directory. This allows consumers to get quick prototype with `carbon-components-react` without scaffolding the build tool-chain.
**Changed**
- CJS build now support UMD, while keeping compatible as CJS.
=> [RFC] feat: support UMD

src/components/TextArea/TextArea.js
**New**
- N/A
**Changed**
- Added `hideLabel` to `TextArea`. This change would make `TextArea` label hiding consistent with `TextInput`, and `Select`.
**Removed**
- N/A
=> fix: added hideLabel prop to TextArea

src/components/InteriorLeftNav/InteriorLeftNav.js
Click handler seems to run upon keypress on the toggle button, and handling keypress causes running the event handler twice.
Refs carbon-design-system/carbon-addons-cloud#21.
**Removed**
- The `keypress` handler on the toggle of `<InteriorLeftNav>`.
=> fix(InteriorLeftNav): remove keypress handler

src/components/Icon/Icon.js, src/components/OverflowMenu/OverflowMenu.js, src/components/Tooltip/Tooltip-story.js, src/components/Tooltip/Tooltip-test.js, src/components/Tooltip/Tooltip.js, src/internal/FloatingMenu.js
Did the following noted in the changelog. These would make us easier to make future enhancement to `<FloatingMenu>`, easing the complexity introduced to support code paths of with/without React portal API.
**New**
* Enhanced `menuOffset` prop in `<FloatingMenu>` to support a callback to return the offset, e.g. to give `<OverflowMenu>` a chance to calculate the adjustment of non-centered menu arrow
* Enhanced `<Icon>` so that `<svg>` in it can be grabbed, to allow calculating tooltip position based on that, and the padding in the outer container doesnot affect the positioning
**Changed**
* Some changes to calculate the position in the right phase in the component lifecycle
* Hoisted several logic as non-class functions so that they are independent of class state
* Hidden tooltips are now …
=> refactor(FloatingMenu): improved position calculation logic

src/components/DatePicker/DatePicker.js
Flatpickr does not change the position of calendar dropdown once it's created, even after the element containing the triggering element (`<input>`) is scrolled.
Flatpickr allows specifying the DOM node the calendar dropdown is inserted into, which would work as a way to alleviate such scrolling issue, for example, by specifying a DOM element being scrolled along with the triggering element.
This change adds a prop that will be passed along to Flatpickr as such DOM node.
Fixes #357.
**New**
- `appendTo` prop, that is passed along to Flatpickr.
=> feat(DatePicker): allow specifying the DOM node the calendar dropdown is inserted into

src/components/TextInput/TextInput.js
React warning throws if casing is off.
Pretty self explanatory. Without this fix, this warning shows:
```
Warning: Unknown ARIA attribute aria-describedBy. Did you mean aria-describedby?
```
=> fix(TextInput): aria-describedby casing

CONTRIBUTING.md
**New**
Added  ` to .gh-pages/coverage
**Changed**
Added backticks to the location of this folder: .gh-pages/coverage
**Removed**
Nothing removed
=> Fix on format on .gh-pages/coverage folder

src/components/FileUploader/FileUploader-story.js, src/components/FileUploader/FileUploader-test.js, src/components/FileUploader/FileUploader.js
The input type=file has an attribute, `accept`, that allows the user to set which file types the input accepts. It doesn't actually prevent upload of other files, but it does make the user's process of finding files that will be accepted easier.
Reference:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
=> feat(fileUploaded): Added accept attribute

src/components/Slider/Slider.js
Fixes #645.
**Changed**
- Fires `onChange` when there is a change in `<input>`.
=> fix(Slider): fire onChange on change in input element

src/components/PaginationV2/PaginationV2.js
Instead of placing a `|` with no padding, it will now render nothing. Added some conditional styles to prevent a double border / outline being hidden under other button.
Closes https://github.com/carbon-design-system/carbon-components-react/issues/637
=> fix(pagination): remove | when pageInputDisabled is true

src/internal/FloatingMenu.js
Fixes #573.
**Changed**
- The React portal container element for floating menu from `<body>` to a pseudo `<div>`. The contents in the such pseudo `<div>` is moved to `<body>` once the portal content is mounted.
**Removed**
- The original `<div>` around the floating menu.
=> fix(FloatingMenu): remove wrapper div for portal

src/components/Slider/Slider.js
Refs #645. Addresses https://github.com/carbon-design-system/carbon-components-react/issues/645#issuecomment-368619856, ensuring emitting number for `onChange`.
**Changed**
- The value of `onChange` upon change in `<input>` is now a number, instead of a string.
=> fix(Slider): ensure emitting number with onChange

src/components/MultiSelect/MultiSelect.js
Adds in the `type` `PropType` for the `MultiSelect` component
=> docs(multiselect): add type PropType definition

src/components/Dropdown/Dropdown-story.js, src/components/Dropdown/Dropdown-test.js, src/components/Dropdown/Dropdown.js
Closes carbon-design-system/carbon-components-react#655
**New**
- To the `Dropdown` component, added two new properties `onOpen` which is called with no arguments when the dropdown is opened, and `onClose` which is called with no arguments when the dropdown is closed.
- Added these to `Dropdown-story.js` for demonstration purposes too.
- Tests.
=> feat(Dropdown): Add onOpen and onClose props

src/components/Modal/Modal.js, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
Closes carbon-design-system/carbon-components-react#599
Adds WAI-ARIA role to `Modal` 
**New**
* `role="dialog"` to the inner `Modal` container
=> fix(modal): add role to inner modal content

src/components/CodeSnippet/CodeSnippet.js
Closes #602 
Added `role` and `tabIndex` to the snippet container so you can focus on it using the keyboard, and use the arrow keys to scroll the content.
**Changed**
* `CodeSnippet.js`
=> fix(code-snippet): fixed keyboard interaction

src/components/Form/Form-story.js
Closes carbon-design-system/carbon-components-react#612
a11y fixes for `Form` 
**New**
- `FileUploader` button now has text 
- Added a third `RadioButton` to help illustrate keyboard navigation within a `RadioButtonGroup`
**Changed**
- Ensured each form item has a unique id
=> fix(form): a11y fixes for form in storybook

.storybook/Container.js
Closes carbon-design-system/carbon-components-react#611
Closes https://github.com/carbon-design-system/carbon-components-react/issues/616
**New**
- `role="main"` added to the main storybook `Container`
=> fix(container): add role of main to storybook container

README.md, src/components/Tooltip/Tooltip-test.js, src/components/Tooltip/Tooltip.js
Closes carbon-design-system/carbon-components-react#669
support control tooltip open state by `props.open`
**Changed**
* update tooltip internal open state when the prop `open` changed
=> feat: support control tooltip open state with prop

src/components/Loading/Loading.js
Fixes #650.
**New**
* Support for `bx--loading-overlay--stop` CSS class.
=> fix(Loading): add missing bx--loading-overlay--stop class

src/components/RadioTile/RadioTile.js, src/components/Tile/Tile-story.js, src/components/Tile/Tile-test.js, src/components/Tile/Tile.js, src/components/TileGroup/TileGroup.js
Closes carbon-design-system/carbon-components-react#681
This swaps single select and multiselect border styles
**Changed**
* swapped single select and multiselect styles
* ensure omitted tiles do not break rendering
=> fix(multi-select): swap selectable, multi select styles. Bug fixes

src/components/DataTable/DataTable.js, src/components/DataTable/TableHeader.js, src/components/DataTable/__tests__/TableHeader-test.js, src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableHeader-test.js.snap
Closes carbon-design-system/carbon-components-react#691
Add isSortable to provide un-sorted headers
**New**
**Changed**
* `TableHeader`
* Now includes `isSortable` prop that defaults to false that will toggle which header will get rendered
* `DataTable#getHeaderProps` now adds `isSortable: true` to props passed into TableHeader
**Removed**
=> fix(DataTable): add isSortable to provide un-sorted headers

src/components/FileUploader/FileUploader-test.js, src/components/FileUploader/FileUploader.js
**BUG**
The FileUploader component currently doesn't allow you to delete a file and then reupload the exact same. The value of `<input type=file ...` isn't reset.
Steps to reproduce:
1. Navigate to the FileUploader: http://react.carbondesignsystem.com/?selectedKind=FileUploader&selectedStory=FileUploader&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
2. Upload a file
3. Click the X or the Clear Files button to clear the file
4. Upload the same file again
5. The file doesn't upload a second time
**FIX**
As advised by:
https://stackoverflow.com/questions/39484895/how-to-allow-input-type-file-to-select-the-same-file-in-react-component
Add an onClick listener to the input file element that clears the value of the element.
=> fix(FileUploader): Reset the internal value so onChange works as expected

src/components/Tooltip/Tooltip-test.js, src/components/Tooltip/Tooltip.js
Closes #669.
Refs carbon-design-system/carbon-components#266.
This PR is for preventing tooltip from being closed when the mouse is on the open tooltip.
**New**
* Code to detect if the mouse is is on the open tooltip
* Code to debounce event handlers that open/close tooltip (Moving mouse cursor from the trigger button to the open tooltip causes mouse pointer to go to another element between them, and thus detecting mouse position right after the mouse cursor goes out of the trigger button will detect another element)
=> feat(Tooltip): handle hover-over on tooltip

src/components/Notification/Notification-story.js, src/components/Notification/Notification-test.js, src/components/Notification/Notification.js
Sometimes we don't want to be able to close a notification.
**New**
* `closable` prop on notification components (InlineNotification, ToastNotification)
=> feat(Notification): Support non-closable notifications

src/components/DatePickerInput/DatePickerInput.js
Closes carbon-design-system/carbon-components-react#720
Fixes an issue where an error would be thrown if the onClick prop was not set.
**New**
* Adds a default onClick prop to `<DatePickerInput />`
**Changed**
* N/A
**Removed**
* N/A
=> fix(DatePickerInput): add default onClick prop

src/components/DataTable/DataTable.js, src/components/DataTable/__tests__/DataTable-test.js
Closes carbon-design-system/carbon-components-react#712
In a DataTable that uses a TableBatchActions, clicking the Cancel button will deselect all items as well as hiding the batch actions toolbar
**Changed**
* Cancel button deselects items in a table
=> fix(DataTable): Cancel deselects all

src/components/DataTable/DataTable.js, src/components/DataTable/__tests__/DataTable-test.js, src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/DataTable/state/__tests__/getDerivedStateFromProps-test.js, src/components/DataTable/state/__tests__/sorting-test.js, src/components/DataTable/state/getDerivedStateFromProps.js, src/components/DataTable/state/sorting.js, src/components/DataTable/tools/__tests__/sorting-test.js, src/components/DataTable/tools/sorting.js
Closes carbon-design-system/carbon-components-react #705 
Changes to make DataTable preserve the sort when it is re-rendered. This includes re-sorting the rows when new props are received
**New**
* getCurrentSortState - Returns the sorted state based on the current sort options in the state
**Changed**
* DataTable.componentWillReceiveProps - Now triggers a resort of new data based on sort options in state, this is to preserve sort
=> feat(DataTable): Preserve sorting in DataTable when it is re-rendered

src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/DataTable/tools/__tests__/__snapshots__/normalize-test.js.snap, src/components/DataTable/tools/normalize.js
DataTable, the `rows` argument in the renderProp has a new prop in the `cells` array. The `cell` object has a new `info` property with an object value of `{ header : string }` which can indicate the key of the header. Useful to determine the current column for side-effects.
Closes carbon-design-system/carbon-components-react#737
**New**
* `row.cells[]` objects have a new `info.header` property to indicate the header key of the current cell.
Signed-off-by: Andrew J Daniel <andrewjd1@gmail.com>
=> feat(DataTable): Row cell has header key

src/components/NumberInput/NumberInput.js
Closes carbon-design-system/carbon-components-react#759
Ideally, this comment would be added in the Description column in proptypes table in the NumberInput Storybook, but I'm not sure how to do that?
**Changed**
* Updated NumberInput `onChange` docs
=> docs(NumberInput): add a comment on how to access the new value in onChange (#759)

src/components/RadioTile/RadioTile-test.js, src/components/RadioTile/RadioTile.js
`label` in `RadioTile` now accepts className via Props
**New**
```
static propTypes = {
checked: PropTypes.bool,
className: PropTypes.string,
defaultChecked: PropTypes.bool,
id: PropTypes.string,
name: PropTypes.string,
onChange: PropTypes.func,
value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
};
```
**Changed**
* `className: PropTypes.string`
**Removed**
* N/A
=> fix(RadioTile): Accepts className in props

src/components/DataTable/DataTable-story.js, src/components/DataTable/DataTable.js, src/components/DataTable/__tests__/DataTable-test.js, src/components/DataTable/state/__tests__/getDerivedStateFromProps-test.js, src/components/DataTable/state/__tests__/sorting-test.js, src/components/DataTable/state/getDerivedStateFromProps.js, src/components/DataTable/state/sorting.js, src/components/DataTable/tools/normalize.js
Closes #740 
Adds an extra check in the `cWRP` hook that will check to see if there are additional rowIds in the `nextState` and will update state accordingly, if so.
**New**
**Changed**
* `DataTable`
* Add behavior to `cWRP` to validate rowIds
* Add corresponding tests for bugfix
* Add `with dynamic rows` story to `DataTable-story`
**Removed**
=> fix(DataTable): update state properly in componentWillReceiveProps

src/internal/FloatingMenu.js
Override style of default render to position offscreen to the right
to prevent the window.scrollY from being affected right before
measuring the size of the menu.
This seems to only be an issue in the latest version of react (16.3) probably
due to the asynchronous rendering changes.
=> fix(floating-menu): positioning in scrollable container maintained

src/components/Checkbox/Checkbox-story.js, src/components/Checkbox/Checkbox.js, src/components/OverflowMenuItem/OverflowMenuItem.js
It's more useful to be able to set the classname on the wrapping element
(which can be used to address internal elements)
This will go some way to enable more dynamic theming options.
**New**
* `wrapperClassName` prop on OverflowMenuItem and Checkbox.
=> feat(checkbox/overflow-menu): Support wrapping classes

src/components/ListBox/ListBoxSelection.js, src/components/ListBox/__tests__/__snapshots__/ListBoxField-test.js.snap, src/components/ListBox/__tests__/__snapshots__/ListBoxSelection-test.js.snap
This prevents a weird issue in IE where focus on the svg causes an
exception in downshift.
The issue occurs only in IE. Basically, downshift tries to manage focus after the input loses focus, and if the element is an SVG, downshift has a fit. This quick fix prevents that on our side.
=> fix(list-box): Prevent focus on icon inside selection

src/components/TooltipSimple/TooltipSimple.js
Closes #786
Add condition to handle case when the tooltip icon not displaying
**New**
The TooltipSimple without the icon is displayed 
**Changed**
**Removed**
=> fix(TooltipSimple): handle case when the tooltip icon not displaying

src/components/DatePickerInput/DatePickerInput.js
Add default `onChange` prop in `DatePickerInput` - This fix is similar to the one that has been done for #720 
**New**
```
static defaultProps = {
pattern: 'd{1,2}/d{1,2}/d{4}',
type: 'text',
disabled: false,
invalid: false,
labelText: '',
onClick: () => {},
onChange: () => {},
};
```
**Changed**
```
static defaultProps = {
pattern: 'd{1,2}/d{1,2}/d{4}',
type: 'text',
disabled: false,
invalid: false,
labelText: '',
onClick: () => {},
};
```
**Removed**
N/A
=> fix(DatePickerInput): add default onChange prop

src/components/DatePicker/DatePicker-story.js, src/components/DatePicker/DatePicker.js
Also prevent onChange event from being placed on the any other element.
**Changed**
* datepicker `onChange` prop triggers properly when provided the `value` prop. So the onChange event on the datepicker is only called when a date is selected and not on input change. Input change can be caught on datepicker-input.
=> fix(date-picker): Provide examples for fully controlled datepicker

src/components/DatePicker/DatePicker-story.js, src/components/DatePickerInput/DatePickerInput.js
The default pattern for the input should be a valid regexp.
I don't know if the intention was to be `\d{1,2}\d{1,2}\d{4}` or if it was to be separated by /s or not.
**Changed**
* Default `pattern` prop on DatePickerInput is now a valid regexp
=> fix(date-picker-input): default pattern is faulty

src/components/OverflowMenu/OverflowMenu-test.js, src/components/OverflowMenu/OverflowMenu.js
Closes carbon-design-system/carbon-components-react#818
Allow menu items to be selected by pressing Space/Enter. Previously the key handler caused the menu to close, before the menu items had chance to handle the event. But the menu closes when tabbing out of the menu, so the handler is only needed to open the menu, not to close it.
The fix can be seen from the OverflowMenu storybook - without the fix, selecting menu items using the keyboard doesn't show anything in the Action Logger, but with the fix the onClick action is fired.
**Changed**
* Accessibility fix: Allow overflow menu items to be selected by pressing Space/Enter
=> fix(OverflowMenu): allow key events to be handled by menu items

src/components/OverflowMenu/OverflowMenu.js
Refs #841.
**Changed**
* Better documentation for `floatingMenu` prop in `<OverflowMenu>`.
=> docs(OverflowMenu): more docs on floating mode

src/components/DatePicker/DatePicker-story.js, src/components/DatePicker/DatePicker-test.js, src/components/DatePicker/DatePicker.js
**Summary**:
Add the flatpickr locale support (https://flatpickr.js.org/localization/) for the DatePicker component. This update will allow for a new prop `locale` to be passed to support the following languages. https://github.com/flatpickr/flatpickr/tree/master/src/l10n
**Examples**:
**Changed**
* Add locale prop to DatePicker to support multiple languages.
=> feat: add language locale prop to DatePicker for global use

src/components/PaginationV2/PaginationV2-test.js, src/components/PaginationV2/PaginationV2.js
It works as `itemsPerPageText` and colon combined, that allows consumer to translate the combination.
Fixes #835.
**New**
* `itemsPerPageFollowsText ` prop
**Changed**
* `PaginationV2-test.js` that used to test older `<Pagination>` - Changed to actually test `<PaginationV2>`
=> feat(PaginationV2): introduce itemsPerPageFollowsText prop

src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap, src/components/ListBox/ListBox.js, src/components/ListBox/__tests__/__snapshots__/ListBox-test.js.snap, src/components/MultiSelect/__tests__/__snapshots__/FilterableMultiSelect-test.js.snap
Closes carbon-design-system/carbon-components-react#569
**New**
**Changed**
* Removes `bx--form-item` from base `ListBox` component
**Removed**
=> fix(DropdownV2): remove form-item class from base ListBox

src/components/PaginationV2/PaginationV2.js
Closes #778
fix spacing discrepancy (Carbon Vanilla vs. React)
**New**
**Changed**
* Remove the space added after the text
**Removed**
=> fix(PaginationV2): adjust spacing, resolves #778

package.json, src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap, src/components/ListBox/ListBox.js, src/components/ListBox/__tests__/__snapshots__/ListBox-test.js.snap, src/components/MultiSelect/__tests__/MultiSelect-test.js, src/components/MultiSelect/__tests__/__snapshots__/FilterableMultiSelect-test.js.snap, yarn.lock
Closes carbon-design-system/carbon-components-react#600
**New**
**Changed**
* `package.json`
* Updated `downshift` dependency
* `src/components/ListBox`
* Now prevents event propagation for key events through `onKeyDown`
**Removed**
=> fix(ListBox): prevent key events from propagating

src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableToolbarSearch-test.js.snap, src/components/Search/Search-test.js, src/components/Search/Search.js
Closes https://github.com/carbon-design-system/carbon-components-react/issues/830
Adds a button as a wrapper around the `clear` icon for a11y purposes
**New**
- The clear button  can now receive keyboard focus
**Changed**
- Updated tests
**Testing**
- Try tabbing to the `clear` icon when text has been entered
=> fix(search): add button to clear icon for a11y

manifest.yml
local manifest.yml got merged in accidentally.
=> chore: Revert manifest.yml to correct routes

config/jest/jsTransform.js
Follow-up fix of https://github.com/carbon-design-system/carbon-components-react/pull/886, applying a similar fix to babel config for test.
**Changed**
* Add `decoratorsLegacy: true` to stage-1 preset in babel config for test
=> chore(build): fix babel config for test

src/components/DatePicker/DatePicker.js
Fixes #491.
**Changed**
* A change to treat Flatpickr's default export as a constructor.
=> fix(DatePicker): treat Flatpickr's default export as a constructor

src/components/DatePicker/DatePicker-test.js, src/components/DatePicker/DatePicker.js
Closes https://github.com/carbon-design-system/carbon-components-react/issues/898
Seeing console errors displaying while using the DatePicker and passing in minDate and maxDate props. 
**New**
* N/A
**Changed**
* DatePicker.js - adding minDate and maxDate to props-type and render function
* DatePicker-test.js - adding tests for minDate and maxDate to prevent the issue. 
**Removed**
* N/A
=> fix: console.errors coming from using Datepicker

src/components/DataTable/TableToolbarSearch.js, src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableToolbarSearch-test.js.snap
Closes carbon-design-system/carbon-components-react#837
Add i18n support for `TableToolbarSearch`
**New**
**Changed**
* `TableToolbarSearch`
* Now has `translateWithId` prop with default prop fallback for translating label text and placeholder text
**Removed**
=> fix(table-toolbar-search): add i18n support

src/components/OverflowMenu/OverflowMenu.js
Fixes #628.
**New**
* Code checking for floating menu in `<ClickListener>` handler in `<OverflowMenu>`
=> fix(OverflowMenu): fix <ClickOutside> not covering floating menu

src/index.js
Export was missing for the IconSkeleton component
=> fix(icon-skeleton): Add missing export for IconSkeleton component

src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableToolbarSearch-test.js.snap, src/components/Search/Search.js
Fixes #923.
**Changed**
* Using `labelText`/`closeButtonLabelText` for the corresponding icon descriptions in `<Search>`
=> fix(Search): make search icon description translatable

src/components/Tooltip/Tooltip.js
Fixes #913.
**Changed**
* The `<Tooltip>` code now does not set `area-owns` unless it’s open
=> fix(Tooltip): prevent aria-owns attribute being set unless the target really exists

src/components/Tile/Tile-test.js, src/components/Tile/Tile.js
Closes carbon-design-system/carbon-components-react#933
This PR will update the chevron inside of an ExpandableTile component to display a description of "Expand" when the tile is collapsed, and "Collapse" when the tile is expanded.
**Changed**
* ExpandableTile chevron Icon now changes description based on the `expanded` state of the component.
=> fix(ExpandableTile): improve the description for the chevron (#933)

.storybook/.babelrc, config/jest/jsTransform.js, config/jest/setup.js, package.json, src/components/Card/Card.js, src/components/CardActionItem/CardActionItem.js, src/components/CardActions/CardActions.js, src/components/CardContent/CardContent-test.js, src/components/CardContent/CardContent.js, src/components/CardFooter/CardFooter.js, src/components/CardStatus/CardStatus.js, src/components/DetailPageHeader/DetailPageHeader.js, src/components/InteriorLeftNav/InteriorLeftNav.js, src/components/InteriorLeftNavItem/InteriorLeftNavItem.js, src/components/InteriorLeftNavList/InteriorLeftNavList.js, src/components/Module/Module.js, src/components/OrderSummary/OrderSummary.js, yarn.lock
Adds `babel-plugin-dev-expression` to add in `__DEV__` time checks that warn about deprecated component usage.
**New**
**Changed**
**Removed**
=> feat(package): add deprecation notices for components

src/components/DataTable/TableHeader.js
Altered Prop~Types for DataTable.TableHeader to prevent warnings when a user supplies a React Element as the child of the TableHeader, currently it only allows a string and hence no custom styling
=> Enhancement: Allow React elements in DataTable.TableHeader

src/components/DatePickerInput/DatePickerInput.js
Closes carbon-design-system/carbon-components-react#905
Added `defaultDate` in props so that we can preload dates.
**New**
Added `defaultDate` in props
=> feat:(DatePickerInput) — add defaultDate option

src/components/DropdownV2/Dropdown.Skeleton.js
Closes https://github.com/carbon-design-system/carbon-components-react/issues/946
Change from `class` to `className`
=> fix(dropdown-skeleton): fix class typo

.storybook/Container.js, package.json, src/components/AccordionItem/AccordionItem.js, src/components/ComboBox/ComboBox.js, src/components/ComposedModal/ComposedModal.js, src/components/DataTable/DataTable.js, src/components/DatePicker/DatePicker.js, src/components/DetailPageHeader/DetailPageHeader.js, src/components/Dropdown/Dropdown.js, src/components/FileUploader/FileUploader.js, src/components/InteriorLeftNav/InteriorLeftNav.js, src/components/NumberInput/NumberInput.js, src/components/OverflowMenu/OverflowMenu.js, src/components/Pagination/Pagination.js, src/components/PaginationV2/PaginationV2.js, src/components/ProgressIndicator/ProgressIndicator.js, src/components/RadioButton/RadioButton.js, src/components/RadioButtonGroup/RadioButtonGroup.js, src/components/RadioTile/RadioTile.js, src/components/SearchLayoutButton/SearchLayoutButton.js, src/components/Slider/Slider.js, src/components/StructuredList/StructuredList-test.js, src/components/StructuredList/StructuredList.js, src/components/Tabs/Tabs.js, src/components/Tile/Tile.js, src/components/TileGroup/TileGroup.js, src/components/TimePicker/TimePicker.js, src/components/Tooltip/Tooltip.js, src/tools/withState.js, yarn.lock
Updates the project to use React v16.3, including new features like `forwardRef` and `StrictMode`, in addition to updating the usage of deprecated lifecycle hooks by prefixing them with `UNSAFE_`.
Most likely would be a candidate for v9, or a release post-v9.
=> chore(package): update to React v16.4

src/components/TooltipSimple/TooltipSimple-story.js, src/components/TooltipSimple/TooltipSimple-test.js, src/components/TooltipSimple/TooltipSimple.js, src/components/TooltipSimple/index.js
Adds back in TooltipSimple since this is being deprecated in v9. Also adds in appropriate deprecation notices and recommendations to use either TooltipDefinition, or TooltipIcon, instead.
**New**
* `TooltipSimple`
**Changed**
**Removed**
=> chore: add back in TooltipSimple with deprecation notices

src/components/Notification/Notification-story.js, src/components/Notification/Notification.js, yarn.lock
Closes carbon-design-system/carbon-components-react #846 
This PR will support an optional `timeout` prop in the ToastNotification component. It makes use of the `componentDidMount` React lifecycle method to check if the `timeeout` prop (which is of type `Number`) is truthy. So if the value is `0`, then the toast will persist until the Notification close button is explicitly clicked. Otherwise, the `handleCloseButtonClick` method will be called after the number of milliseconds in the `timeout` prop has elapsed.
**New**
* `timeout` prop on ToastNotification (default 3000ms).
A few things I would like some input on:
Currently, I am setting the default value of the timeout to 3000ms according to the discussion on the issue, but I'd like to know if we would want to keep a default timeout. I …
=> feat(Notification): Add `timeout` prop to ToastNotification, closes #846

src/components/FileUploader/FileUploader-story.js, src/components/FileUploader/FileUploader.js
Closes carbon-design-system/carbon-components-react #945 
This PR will add an optional `name` attribute to the FileUploader and FileUploaderButton so that the input element will receive its value. If no value is provided, then the attribute value defaults to an empty string.
**New**
* add `name` attribute for `FileUploader` and `FileUploaderButton` components
=> feat(FileUploader): Add optional `name` attribute for FileUploader

src/components/ModalWrapper/ModalWrapper.js, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
Closes carbon-design-system/carbon-components-react#989 
This PR will add a default onKeyDown handler to the ModalWrapper so that no errors are logged if the user does not provide an event handler function.
**New**
* default `onKeyDown` prop for ModalWrapper
=> ModalWrapper `onKeyDown` default handler

src/components/DatePicker/DatePicker.js
Fixes [Issue 997](https://github.com/carbon-design-system/carbon-components-react/issues/997) and [Issue 998](https://github.com/carbon-design-system/carbon-components-react/issues/988).
This does the same work as [PR-1000](https://github.com/carbon-design-system/carbon-components-react/pull/1000/files) which is for v5.
- The console error does not occur in Storybook (maybe because that uses React 16) but you can still observe the props added to the `<div>` tag with the React dev-tools.
- Run Storybook and go to the [DatePicker](http://localhost:9000/?selectedKind=DatePicker&selectedStory=range%20with%20calendar%20and%20min%2Fmax%20dates&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel).
- Using React dev-tools to inspect the children of DatePicker will …
=> fix(datepicker): unknown prop on div tag

src/components/Tooltip/Tooltip.js, src/internal/FloatingMenu.js
Fixes #882.
Fixes #895.
This change does two things, described below:
**New**
* Updates the position of trigger button in "click-to-open" scenario
**Changed**
* Uses cross-browser alternative to `scrollY` (`pageYOffset`)
=> fix(FloatingMenu): fix with scrolling

src/components/Button/Button.js, src/components/Modal/Modal.js, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
Closes carbon-design-system/carbon-components-react#827
This PR fixes the issue where the primary actionable element is not focused when a Modal component is opened. To accomplish this, `ref`s are attached to the Modal and Button components so that the primary actionable element can be programmatically referenced and focused.
**Changed**
* Add support for `ref`s in both the Modal and Button components. This will allow for autofocusing of input elements on render.
* Convert `Button` from a stateless functional component to a class component in order to support `ref`s
There are 2 options to solve this issue, and I would like to gather some more opinions about this implementation:
One method would be to added the `autoFocus` attribute to the primary button or the `modalButton` in `Modal.js` …
=> fix(Modal): Focus primary actionable button on modal opening

src/components/OverflowMenu/OverflowMenu.js, src/components/OverflowMenuItem/OverflowMenuItem.js
Closes carbon-design-system/carbon-components-react#991
Unlike its vanilla counterpart, the React basic OverflowMenu does not automatically focus the first menu item when the menu is opened. This PR will add a ref to the first menu item so that focus can be applied when the overflow menu is opened.
**New**
* add `floatingMenu` prop to `OverflowMenuItem`s based on whether or not the `OverflowMenu` is a floating menu
* attach corresponding primary focus data attribute to menu item based on `primaryFocus` and `floatingMenu` props
* add conditional statement to focus primary element in basic `OverflowMenu` based on the new `data-overflow-menu-primary-focus ` prop
=> fix(OverflowMenu): emulate vanilla component behavior

src/components/DataTable/TableExpandRow.js
Closes #995
Add `iconDescription` props to `TableExpandRow` in `DataTable`
The `iconDescription` props that will be used as the Title
=> fix(DataTable): add icon description to TableExpandRow in DataTable

src/components/OverflowMenu/OverflowMenu.js
Closes carbon-design-system/carbon-components-react#1030
Removes unknown prop warning when `OverflowMenu` is rendered
**Changed**
* destructure `onOpen` prop to prevent it from being spread into `<ClickListener>` ([more info on the issue](https://reactjs.org/warnings/unknown-prop.html))
This may be a target for refactoring since it seems that the `onClick` prop has previously been destructured but is unused and ignored by ESLint. Since `other` only contains 4 props (`className`, `onClose`, `onKeyDown`, and `open`), it might be better to explicitly pass along the necessary props to the `<div>` within `<ClickListener>`. Would like to hear some thoughts from the core team about this
=> fix(OverflowMenu): prevent unknown props being spread to `ClickListener`

.storybook/Container.js, src/components/OverflowMenu/OverflowMenu.js, src/components/Tooltip/Tooltip.js, src/internal/FloatingMenu.js
This change makes `<FloatingMenu>` support an element to put the menu into,
which is, the ancestor of the trigger button with `data-floating-menu-container` attribute.
This change also removes code for React15-, which we dropped the support from 9.x codebase.
Refs carbon-design-system/carbon-components#910.
Refs carbon-design-system/carbon-components#911.
**New**
* New prop in `<FloatingMenu>`, `target`, which takes a function that returns the container the menu should be placed into
* Code in `<OverflowMenu>` and `<Tooltip>` to pass along that new prop, both returning the ancestor of the trigger buttun with `data-floating-menu-container` attribute
* A hidden `<input>` in dev env, to trap keyboard focus. With it, tab navigation of overflow menu closes the menu once the focus goes out of …
=> feat(FloatingMenu): support for specifying target container

src/components/Tab/Tab.js, src/components/Tabs/Tabs.js
Adds some more a11y fixes to `Tab` and `Tabs` to more closely mimic the vanilla component
**New**
- adds `aria-selected` to `Tab` component
- adds `aria-hidden` to `TabContent`
=> fix(tabs): add a11y fixes to tabs

src/components/Loading/Loading.js
Closes https://github.com/carbon-design-system/carbon-components-react/issues/700
Adds `aria-live` attribute for use with JAWS screen reader
**New**
- `aria-live` is either `assertive` or `off` based on active prop
For reference: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
=> fix(loading): add a11y for JAWS

src/components/MultiSelect/MultiSelect.js
Currently the selectedItems does an object to object in-memory comparison which limits it's usage and requires workarounds from the client.  Instead it should compare on an id to id basis.
Closes carbon-design-system/carbon-components-react#901
**New**
**Changed**
* MultiSelect Compare on ids when determining list item selection, not on object to object
**Removed**
=> fix(MultiSelect): SelectedItems should compare on an id to id basis

src/components/MultiSelect/MultiSelect.js, src/components/MultiSelect/__tests__/MultiSelect-test.js
Closes  #1009
The Downshift does not close the menu as long as it contains active elements that have not lost the fucus.
Using the code  useed for the `FilterableMultiSelect` component to resolves this problem
**New**
**Changed**
**Removed**
=> fix(MultiSelect):  close MultiSelect after any option is selected/unselected

src/components/FileUploader/FileUploader.js
Closes carbon-design-system/carbon-components-react#998
The `onChange` method supplied to `FileUploader` is called twice by the component
**Removed**
* Remove duplicate method call
* Remove redundant and unused props
=> fix(FileUploader): `onChange` method called twice

src/components/Tabs/Tabs-story.js
**Changed**
* Corrected typo: "ontent" -> "Content"
=> Fix typo in selected example tabs component

package.json, src/components/OverflowMenu/OverflowMenu-story.js, src/components/OverflowMenuItem/OverflowMenuItem.js, yarn.lock
Adds in a `title` prop to `OverflowMenuItem` that will add the browser default tooltip on text that is expected to be truncated. I felt this was less intrusive than adding `title` on all `OverflowMenuItem` and can be added on a case by case basis. 
Requires https://github.com/carbon-design-system/carbon-components/pull/947 to be merged first
**New**
- `title` prop that will add the browser default tooltip on the text that is expected to be truncated
**Testing**
- Check option 2 of the first `OverflowMenu` example once the PR is the main repo has been merged and pulled in
=> feat(overflow-menu): add requireTitle prop for text that is truncated

src/components/Button/Button.js, src/components/FileUploader/FileUploader.js, src/components/ModalWrapper/ModalWrapper.js, src/prop-types/types.js
Closes carbon-design-system/carbon-components-react#1034
FileUploaderButton propTypes currently only expects `buttonKind` to either be `primary` or `secondary`, but the underlying `Button` component can accept additional `buttonKind` options
**Changed**
* expected propTypes for `<FileUploaderButton>`'s `buttonKind` prop
=> fix(FileUploaderButton): allow more buttonKind options in propTypes

src/components/Checkbox/Checkbox.js
Closes carbon-design-system/carbon-components-react#1059
This PR adds a `title` attribute to the Checkbox component so that users can add alt text to their checkbox labels.
**New**
* `title` attribute on `<Checkbox>`
=> feat(Checkbox): add `title` attribute to checkbox label

package.json, src/components/Select/Select-story.js, src/components/Select/Select-test.js, src/components/Select/Select.js
Closes carbon-design-system/carbon-components-react#1017
This PR will add an `invalid` prop to `Select` to apply data validation styles to the component. Depends on https://github.com/carbon-design-system/carbon-components/pull/919
**New**
* Add `invalid` prop to `Select` component
**Changed**
* If boolean values are falsy, set value to `undefined` so that they are not attached as string `"false"` to the rendered DOM elements
* Fix tests and typos
**Removed**
* Removed conditional logic for determining location of `Select` label. Reflects changes in https://github.com/carbon-design-system/carbon-components/pull/919
=> Add invalid prop to Select

src/components/Pagination/Pagination-test.js, src/components/Pagination/Pagination.js, src/components/PaginationV2/PaginationV2.js
…age label, resolves #1067
This PR fixes issue #1067.  This makes sure that we aren't doing string concatenation that will break localization for languages other than English.
=> fix(pagination): remove string concatenation that will break localization for languages other than English

package.json, yarn.lock
Updates to 4.9.2 instead of 4.9.0 as it doesn't break anything from the original PR (#1052 )
=> Greenkeeper/node sass 4.9.2

src/components/Tabs/Tabs.js
Fixes #1054.
**Changed**
* Closes dropdown when tab item is selected - Instead of toggling.
=> fix(Tabs): ensure dropdown is closed when tab is selected

src/components/Breadcrumb/Breadcrumb-story.js, src/components/Breadcrumb/Breadcrumb.js
Closes #1073 
This adds an optional prop for `Breadcrumbs` called `noTrailingSlash` which conditionally adds the `bx--breadcrumb--no-trailing-slash` class. It also adds a new story for the breadcrumbs component, showcasing this new behavior.
**New**
* `noTrailingSlash` optional prop
=> feat(breadcrumbs): provide ability to disable trailing slash as a prop

src/components/CodeSnippet/CodeSnippet.js
Closes IBM/carbon-components-react #1050 
Adds aria label to codesnippet text box  div. Cannot reproduce issue using DAP or AI but should fix it.
**New**
* add aria label
=> fix(code-snippet): add aria label to textbox

src/components/DataTable/README.md
DataTable Example docs missed an import 
**Changed**
Added missed TableHeader import to Readme.md
=> Missed Table Header Import in readme

.storybook/Container.js, src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap, src/components/ListBox/ListBox.js, src/components/ListBox/__tests__/__snapshots__/ListBox-test.js.snap, src/components/MultiSelect/__tests__/__snapshots__/FilterableMultiSelect-test.js.snap
Closes https://github.com/IBM/carbon-components-react/issues/1086
**Changed**
- `tabindex` to `tabIndex`
- `class` to `className`
=> fix(DropdownV2): fix tabIndex warning

src/index.js
Exports the Tag component. It was removed in a prior PR, but I don't (think) it was actually supposed to be deprecated since it's still in the Storybook and included in the component
**New**
* Exports `<Tag />` and `<TagSkeleton />`
=> Export Tag & TagSkeleton

src/components/Icon/Icon-test.js, src/components/Icon/Icon.js
Fixes https://github.com/IBM/carbon-components-react/issues/1128
Handles an Icon being created without a "name" prop
=> fix(Icon): handle undefined name

src/components/Dropdown/Dropdown-story.js, src/components/Dropdown/Dropdown-test.js, src/components/Dropdown/Dropdown.js
Closes IBM/carbon-components-react#1137
Implements light option for older Dropdown component
**New**
* Added light option in src/Dropdown component, tests, storybook
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/carbon-components-react/1138)
=> fix(Drodown): adds light support

src/components/Modal/Modal.js, src/components/ModalWrapper/ModalWrapper-story.js, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
Closes IBM/carbon-components-react#1123
This PR will allow users to provide a selector that will be focused when the modal is opened. This behavior will be in line with the vanilla component's capabilities.
**New**
* add `selectorPrimaryFocus` prop on `<Modal>`
* include `<ModalWrapper>` Storybook example showing `selectorPrimaryFocus` prop behavior
**Changed**
* modify auto focus behavior based on `selectorPrimaryFocus` value, or use default primary actionable item
=> fix(Modal): add support for primary focus selector prop

src/components/DataTable/TableHeader.js
Closes IBM/carbon-components-react#1026
**New**
**Changed**
* `TableHeader` now passes `className` to underlying `th`
**Removed**
=> fix(TableHeader): apply className to outer th node

src/components/DataTable/DataTable.js
Closes IBM/carbon-components-react#878
**New**
**Changed**
* DataTable prop types for headers now matches the `TableHeader` prop type.
**Removed**
=> feat(DataTable): loosen prop-type definition to include nodes

src/internal/FloatingMenu.js
Fixes #1066.
**Changed**
* A change to ensure that `<FloatingMenu>`’s `onPlace` callback is called in React 15.
=> fix(FloatingMenu): fix missing onPlace callback for React 15

src/components/Modal/Modal.js, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
Closes IBM/carbon-components-react#1180 
**Changed**
* destructure `selectorPrimaryFocus` prop to prevent it from being spread in child elements
=> fix(Modal): remove console warning for `selectorPrimaryFocus` prop

src/components/FileUploader/FileUploader-story.js
Closes IBM/carbon-components-react#1199
**Changed**
* modified `<FileUploader>` storybook examples to render and avoid logging errors to console
=> docs(FileUploader): fix failing storybook example

src/components/FileUploader/FileUploader-story.js
Restore 'none' `buttonKind` knob which was mistakenly replaced by defaulting to `buttonKind="primary"` in #1200 
Related: #1199
=> docs(FileUploader): restore 'none' `buttonKind` knob

src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap, src/components/ListBox/ListBox.js, src/components/ListBox/__tests__/__snapshots__/ListBox-test.js.snap, src/components/MultiSelect/__tests__/__snapshots__/FilterableMultiSelect-test.js.snap
Closes #1192
This change adds a default aria label to list boxes so we can pass the DAP tests.
This change also adds that new aria label to unit tests.
=> fix: Added an aria label to the list box, resolves #1192.

src/components/RadioButton/RadioButton.js, src/components/Slider/Slider.js, src/components/TimePicker/TimePicker.js, src/components/TimePickerSelect/TimePickerSelect.js, src/components/ToolbarSearch/ToolbarSearch.js
Fixes #1206.
**Changed**
* `labelText` properties of several components from `PropType.string` to `PropType.node`.
=> feat(components): allow React node in labels

src/components/NumberInput/NumberInput-story.js, src/components/NumberInput/NumberInput-test.js, src/components/NumberInput/NumberInput.js, src/components/Select/Select-story.js, src/components/Select/Select-test.js, src/components/Select/Select.js, src/components/TextArea/TextArea-test.js, src/components/TextArea/TextArea.js, src/components/TextArea/Textarea-story.js, src/components/TextInput/TextInput-story.js, src/components/TextInput/TextInput-test.js, src/components/TextInput/TextInput.js
Adds support for helper text element in TextInput, Select and NumberInput components. See [Carbon Design System](http://www.carbondesignsystem.com/components/text-input/code) for reference.
**Changed**
* {{TextInput}}: new {{helperText}} property
* {{NumberInput}}: new {{helperText}} property
* {{Select}}: new {{helperText}} property
=> feat(TextInput): add support for helper text

src/components/Checkbox/Checkbox.js
The signature for the onChange function of the Checkbox component doesn't really jive with the rest of the inputs. Having the true/false value as the first parameter is confusing when other components pass in events or descriptive objects as the first parameter. Without diving into the source or observing the action log in the Storybook, the 2nd and 3rd parameters aren't obvious. This PR adds a description to the docs to make the method signature more apparent.
A future fix might update the component to coalesce the three parameters into a single one to make more obvious the parameters that are being passed in. This might also be the standard signature for checkbox components and I'm just not hip on it haha.
**New**
* Checkbox onChange description
=> docs(Checkbox): Add description to checkbox onChange function

src/components/DataTable/Table.js, src/components/DataTable/__tests__/Table-test.js, src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/DataTable/__tests__/__snapshots__/Table-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableBody-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableCell-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableExpandHeader-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableExpandRow-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableHead-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableHeader-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableRow-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableSelectAll-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableSelectRow-test.js.snap
Fixes #1205.
**New**
* `zebra` prop to `<Table>`, whose default is `true`. Setting `false` there disables zebra striping.
* Support for dynamic CSS class names in Data table's `wrapComponents` internal helper.
=> feat(DataTable): support disabling zebra stripe

src/components/DataTable/DataTable.js
Small QOL fix to allow folks to pass in `isSortable` to `getHeaderProps` and have that pass through to the underlying `TableHeader` component.
**New**
**Changed**
* `getHeaderProps` now reads `isSortable` from arguments passed in, defaulting to true
**Removed**
=> feat(data-table): allow isSortable to be defined in getHeaderProps

src/components/StructuredList/StructuredList-story.js
Adds addon-info storybook implementation with text descriptions.
Closes IBM/carbon-components-react#1229
**New**
* Add `@storybook/addon-info` implementation to the `StructuredList` stories
* Add `... withInfo` with text descriptions, similar to what's done in other components in this repo
**Changed**
* Indentation to accommodate `addons-info` implementation
=> fix(structured-list): add storybook addon-info

.storybook/manager-head.html
Closes IBM/carbon-components-react#1236
This adds some meta tags to improve search results/sharing of Carbon Components React. At this time, Storybook doesn't offer an option to change the page title so it needs to be done with a script tag. Tacking on a second title tag is a no-op.
**New**
* `manager-head.html` is the escape hatch provided by Storybook for this sort of thing.
=> docs: update meta tags on root html

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md, package.json
Closes IBM/carbon-components-react#1259
@storybookaddon-options was added as a regular dependency when it should have been a dev dependency.
**Changed**
* @storybook/addon-options from `dependencies` to `devDependencies`
=> docs(Storybook): switch @storybook/addon-options to dev dependency

src/components/FileUploader/FileUploader-story.js
This reverts commit 052822271c4663c153e25bd92f00ccb49e278153.
After a discussion with @asudoh who brought the issue to the rest of the core carbon team, it was decided that the values of `buttonKind` in the `FileUploaderButton` should be in sync with regular `Button`. This commit will revert the change that allowed `FileUploaderButton` to have a null value for the `buttonKind` prop in the Storybook example
=> Revert "docs(FileUploader): restore 'none' `buttonKind` knob (#1202)"

src/components/ComboBox/ComboBox.js
Closes IBM/carbon-components-react#1258
Update `ComboBox` to pass along `translateWithId`
**New**
**Changed**
* Update `ComboBox` to pass along `translateWithId`
**Removed**
=> feat(combo-box): add support for translateWithId

src/components/Modal/Modal.js
As focus-wrap behavior is for handling focus on an element outside modal.
IE11 behaves as though window lost focus when focus goes onto `<select>`, which causes an adverse effect if such `<select>` is in a modal.
Fixes #1257.
**Changed**
* Stopped running "focus-wrap" behavior in modal if browser window loses focus (aligned with vanilla).
=> fix(Modal): no focus-wrap for "window lost focus" condition

src/components/ComboBox/ComboBox.js
Closes IBM/carbon-components-react#1161
Added props in a ComboBox component to let users validate the selected value.
**New**
* `invalid` prop in a `comboBox` component
* `invalidText` prop in a `comboBox` component
=> feat(ComboBox): add invalid and invalidText props

src/components/DatePicker/DatePicker-story.js, src/components/DatePicker/DatePicker.js, src/components/DatePickerInput/DatePickerInput.js
Closes IBM/carbon-components-react#1288
I've added a new prop in DatePicker and DatePickerInput that is passed down to icon component and used as a description.
**New**
* new `iconDescription` prop in DatePicker component
* new `iconDescription` prop in DatePickerInput component
**Changed**
* props in `single with calendar` story
* props in `range with calendar` story
=> fix(DatePicker&DatePickerInput): add customizable iconDescription

src/components/Tile/Tile.js
Closes IBM/carbon-components-react#1297
Added an initial state for ClickableTile component to prevent warning.
`Warning: 'ClickableTile' uses 'getDerivedStateFromProps' but its initial state is undefined. This is not recommended. Instead, define the initial state by assigning an object to 'his.state' in the constructor of 'ClickableTile'. This ensures that 'getDerivedStateFromProps' arguments have a consistent shape.
`
**New**
* initial state for ClickableTile component
=> fix(ClickableTile): add initial state to prevent warnings

src/components/Modal/Modal.js, src/components/ModalWrapper/ModalWrapper-test.js, src/components/ModalWrapper/ModalWrapper.js, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
Closes IBM/carbon-components-react#1298
This PR will return focus to the element that launches the modal when the modal is closed, which should improve keyboard a11y. This is accomplished by attaching a ref to the trigger button, which is then used to focus on the button in the callback of the `setState` operation when closing the modal
**New**
* attach a ref to the `<Button>` in `<ModalWrapper>` which will launch the `<Modal>` element
* add logic to call `HTMLElement.focus()` on the button after modal is closed
**Changed**
* access `<Modal>` refs through the refs' `current` property
=> feat(ModalWrapper): return focus to modal trigger button on modal close

src/components/DatePicker/DatePicker.js
Closes IBM/carbon-components-react#1305
When flatpicker detects a mobile device, it doesn't render its own elements.
When Carbon tries to add its custom classes to those non-existing elements, an TypeError (`calendarContainer is undefined`) occurred.
Now we check if the elements exist first, before adding classes.
---
I would like to add a test for this, but don't know how to specify the userAgent for this. [(I already asked this in the issue)](https://github.com/IBM/carbon-components-react/issues/1305#issuecomment-421265249)
=> fix(DatePicker): prevent TypeError on mobile device

src/components/DatePicker/DatePicker.js, src/components/DatePickerInput/DatePickerInput.js
Closes IBM/carbon-components-react#1290
Calendar now can be opened by clicking on calendar icon.
**New**
* new `openCalendar` prop gets passed down to `DatePickerInput` and lets you open a calendar.
=> fix(DatePicker): open calendar on icon click

src/components/FileUploader/FileUploader.js
Closes IBM/carbon-components-react#1334
This PR sets a negative `tabIndex` value on the file input element to prevent it from being focusable on sequential keyboard navigation, while still allowing it to be focused programmatically
**New**
* set negative `tabIndex` on `<input type="file" />` in `FileUploaderButton
=> fix(FileUploaderButton): prevent from being focusable with keyboard

src/components/Tile/Tile.js
Added empty state object to suppress warning and removed some validation that was not needed anymore.
**New**
* Empty state object
**Removed**
* Empty state validation
=> fix(ExpendableTile): add initial state to prevent warnings

src/components/ComboBox/ComboBox.js, src/components/ListBox/ListBox.js
addresses IBM/carbon-components-react#1100
Adds support for light option on `ComboBox`. matches `Dropdown`. (issue number **3** described in the issue https://github.com/ibm/carbon-components-react/issues/1100 )
**New**
* adds option for `light` to `ComboBox`, as well as cascading properties to get the `ListBox` component to apply appropriate styles.
=> fix(ComboBox): add support for light option

src/components/MultiSelect/MultiSelect-story.js, src/components/MultiSelect/MultiSelect.js, src/components/MultiSelect/__tests__/__snapshots__/MultiSelect-test.js.snap
Closes https://github.com/IBM/carbon-components-react/issues/1393
Adds in the ability to add `title` to a `MultiSelectItem`
**New**
- `title` prop to toggle whether or not a title is added
=> fix(multi-select): add ability to add title tooltip on hover

docs/component-template.md, docs/components.md
Add docs for component README files. We can use this internally for creating the component-specific documentation, or can externalize it as part of our Hacktoberfest plans 🎃 👻 
**New**
*  `docs/components.md`, `docs/component-template.md`
**Changed**
**Removed**
=> docs(components): add docs for component README files

src/index.js
Closes https://github.com/IBM/carbon-components-react/issues/1402
Add missing export for `StructureList.Skeleton`
**New**
* export for Structured List Skeleton component
=> fix(export): add missing export

src/components/MultiSelect/MultiSelect-story.js
Similar update to PR #1450 
Importing `{ action }` from `@storybook/react` is deprecated and will cause a console warning. Almost all of the other components in this library import `{ action }` from  `@storybook/addon-actions` instead. For example: https://github.com/IBM/carbon-components-react/blob/22af70d4ab0d7ab12b68fb7be8e0ca844d139b6c/src/components/Select/Select-story.js#L2-L3
**New**
* Adds `import { action } from '@storybook/addon-actions';`
**Removed**
* Removes `{ action }` from `@storybook/react` import
=> chore(multiselect): replace deprecated @storybook/react action

src/components/ComboBox/ComboBox-story.js
Importing `{ action }` from `@storybook/react` is deprecated and will cause a console warning. Almost all of the other components in this library import `{ action }` from  `@storybook/addon-actions` instead. For example: https://github.com/IBM/carbon-components-react/blob/22af70d4ab0d7ab12b68fb7be8e0ca844d139b6c/src/components/Select/Select-story.js#L2-L3
**New**
* Adds `import { action } from '@storybook/addon-actions';`
**Removed**
* Removes `{ action }` from `@storybook/react` import
=> chore(combo-box): replace deprecated @storybook/react action

src/components/Icon/Icon-test.js, src/components/Icon/Icon.js
Refs IBM/carbon-icons#81.
**New**
* Support for `<polygon points="points">`
=> feat(Icon): support polygon

src/components/SkeletonPlaceholder/SkeletonPlaceholder-story.js, src/components/SkeletonPlaceholder/SkeletonPlaceholder-test.js, src/components/SkeletonPlaceholder/SkeletonPlaceholder.js, src/components/SkeletonPlaceholder/index.js, src/index.js
Closes IBM/carbon-components-react#1313
Adds a new Skeleton component that takes a height and/or width property.
Accompanying PR for the SCSS here: https://github.com/IBM/carbon-components/pull/1202
**New**
* Adds a new `<SkeletonPlaceholder />` component
**Changed**
* N/A
**Removed**
* N/A
=> feat: add SkeletonPlaceholder component

src/components/DataTable/TableRow.js
Closes IBM/carbon-components-react#1398
**New**
* Add isSelected to list of omitted props passed to tr dom elements.
=> fix: Don't pass isSelected to tr dom node.

src/index.js
DatePickerSkeleton export was missing
=> fix: add DatePickerSkeleton to default export

src/components/Toggle/Toggle-story.js, src/components/ToggleSmall/ToggleSmall-story.js
Closes IBM/carbon-components-react#1524
The Toggle control in the Storybook was a controlled component, which made it not work interactively. The text in the small Toggle example refers to an uncontrolled component and the Checkbox examples use an uncontrolled component with different examples for the defaultChecked prop so I modeled the Toggles in the same way.
**Changed**
* Toggle and ToggleSmall stories use an uncontrolled component
=> fix(Toggle): Use uncontrolled Toggle in Storybook

src/components/NumberInput/NumberInput.js
Closes https://github.com/IBM/carbon-components-react/issues/1533
Adds `bx--number--helpertext` when `helperText` is present
=> fix(number-input): add helpertext class when helper text is present

src/components/FileUploader/FileUploader-story.js, src/components/FileUploader/FileUploader-test.js, src/components/FileUploader/FileUploader.js
Closes IBM/carbon-components-react#1334
The FileUploaderButton was allowing users to focus both on the wrapper `div` and the `label` using the keyboard
**Changed**
* moved the button styles off of `<FileUploaderButton>`'s `label` and placed it on the wrapper `div` instead
* set the value of the `label`'s `tabIndex` to `null` if the prop value is falsy so that it won't be focusable
=> fix(FileUploader): remove label tabIndex

.storybook/addons.js
Storybook 4 doesn't appear to show the component name in the show info tab anymore. This re-orders the add-ons to show "story" first when someone view a component to hopefully reduce some confusion 
Side note: will `chore:` trigger a re-release of the storybook or do I need to set to `fix` ?
=> chore: reorder storybook addons to show story first

src/components/ContentSwitcher/ContentSwitcher-story.js
"Butto" → "Button" (add missing 'n')
=> docs(ContentSwitcher) fix tiny typo

src/components/Notification/Notification-story.js, src/components/Notification/Notification-test.js, src/components/Notification/Notification.js, src/components/Notification/a11yIconWarningSolid.js
TODO:
---
Closes IBM/carbon-components-react#1532
This PR will add support for the experimental `<InlineNotification />` and `<ToastNotification />` components
**New**
* add support for experimental `<Notification />` component
**Changed**
* fixed notification icons not appearing for `<ToastNotification />`
* conditionally render icons based on notification type (based on new notification guidelines)
---
An open question: is there a reason for separating the inline and toast notification components rather than consolidating them in a common `<Notification />` component? It seems aside from `timeout`, `caption`, and minor markup changes, the majority of the code is shared between the two types of notifications. Would it be worth deduplicating this code?
=> feat(Notification): add experimental notification

.github/CONTRIBUTING.md
Fixes the internal and external links. Add the most significant requirements to our own docs.
=> docs: Update commit message instructions and links

src/components/DataTable/DataTable-story.js, src/components/DataTable/DataTable.js, src/components/DataTable/Table.js, src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/DataTable/__tests__/__snapshots__/Table-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableBody-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableCell-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableExpandHeader-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableExpandRow-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableHead-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableHeader-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableRow-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableSelectAll-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableSelectRow-test.js.snap, src/components/DataTable/stories/default.js
Adds a prop to data table to toggle the no-border modifier class for users that want to apply the bx--data-table-v2--no-border class.
Loosely related to: IBM/carbon-components#1436
=> feat(data-table): add shouldShowBorder prop to data-table

src/components/InlineCheckbox/InlineCheckbox.js
Closes IBM/carbon-components-react#1500
This PR allows the user to provide an optional `title` to serve as a tooltip for the `<InlineCheckbox>` component
**New**
* `title` prop for `<InlineCheckbox>`
=> feat(InlineCheckbox): allow optional tooltip

src/components/NumberInput/NumberInput-test.js, src/components/NumberInput/NumberInput.js
Closes #1506 
Fix input controls misalignment issue in NumberInput component
Ref: [#1312](https://github.com/IBM/carbon-components/issues/1312)
**New**
* Add `bx--number--nolabel` class when label is hidden
=> Fix number input controls misalignment

src/components/Tooltip/Tooltip.js
Closes IBM/carbon-components-react#1154
according to user reports, `aria-expanded` is not a valid attribute for `div`s without the proper `role` attribute assigned. This PR will add `role="tooltip"` to  `<Tooltip>`s without clickable icons, similar to how https://github.com/IBM/carbon-components-react/pull/532 adds `role="button"` to our `<Tooltip>` components with icons.
**Changed**
* add `tooltip` role to `<Tooltip>`s without icons
=> fix(Tooltip): assign "tooltip" role to Tooltips without clickable icons

package.json, src/components/FileUploader/FileUploader-test.js, src/components/FileUploader/FileUploader.js
Closes IBM/carbon-components-react#1564
Currently the only way to activate the `<input type="file">` on the `<FileUploaderButton />` is by clicking the button label. This PR will allow the user to click any part of the `<FileUploaderButton />` to bring up the file upload prompt.
**New**
* add `onClick` handler for container `<div>`
* add `onClick` handler for file input `<label>`
**Changed**
* stop propagation of event if file input label is clicked
=> fix(FileUploaderButton): handle container div onClick

src/components/Tabs/Tabs.Skeleton.js
In `TabsSkeleton`, the props of `fill-rule` in `svg` should be `fillRule`.
```
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
in svg (created by TabsSkeleton)
```
- Change `fill-rule` in `TabsSkeleton` to `fillRule`.
=> fix(TabsSkeleton): remove console warning error in TabsSkeleton

src/components/ListBox/ListBoxSelection.js, src/components/MultiSelect/MultiSelect.js, src/components/MultiSelect/__tests__/__snapshots__/MultiSelect-test.js.snap, src/internal/Selection.js, src/internal/__tests__/Selection-test.js
Closes #1592
Closes #1596 
This PR will prevent users from modifying `<MultiSelect>` actions while the component is disabled.
**New**
- disabled styles for `<ListBox.Selection>`, dependent on https://github.com/IBM/carbon-components/pull/1508
**Changed**
- break out of `<Selection>` event handlers when component is disabled
=> fix(MultiSelect): prevent modification of disabled multiselect actions

src/components/Modal/Modal-story.js, src/components/Modal/Modal.js
Closes IBM/carbon-components-react#1616
`<Modal />` currently does not focus the primary focus element after initial render. This PR adds a check to the `componentDidMount` life cycle method to call focus on the primary focus element.
**New**
- `componentDidMount` method for calling focus on primary focus element after render
=> feat(Modal): focus primary focus element after component mount

package.json
So ESLint/Prettier runs only against the staged files.
**New**
- `lint:staged`/`prettier:staged` scripts.
**Changed**
- `lint-staged` script to use above script.
=> chore(lint): update lint-staged script

src/components/Notification/a11yIconWarningSolid.js
Closes IBM/carbon-components-react#1593
This PR changes InlineNotification SVG prop names from kebab case to camel case, which will avoid React warnings in console
=> fix(Notification): use valid prop names for InlineNotification

src/components/Notification/Notification.js
Closes IBM/carbon-components-react#1614
This PR removes the icon which was mistakenly added to `<ToastNotification>`
**Removed**
- `<ToastNotifcation>` icon
=> fix(Notification): remove icon for ToastNotification

src/components/OverflowMenu/OverflowMenu-story.js, src/components/OverflowMenuItem/OverflowMenuItem-test.js, src/components/OverflowMenuItem/OverflowMenuItem.js
when an href is passed to an overflowmenuitem it will render an anchor tag instead of a button, so
users can bookmark/hover/etc.
The styling doesn't look quite right because as links the overflow menu items always have underlines... I can make a corresponding change to the `carbon-components` as well
Closes IBM/carbon-components-react#1619
**New**
- OverflowMenuItem renders `<a>` when passed `href`
=> feat(OverflowMenuItem): renders an anchor when passed href

src/components/DatePicker/DatePicker-story.js
Closes IBM/carbon-components-react#1637
- fix typo so that the `DatePickerInput` props from the main prop object can be applied correctly to this story
=> fix(datepicker): apply datepickerinput props properly

src/components/ModalWrapper/ModalWrapper-story.js, src/components/ModalWrapper/ModalWrapper.js, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
Closes IBM/carbon-components-react#1632
This PR exposes the `selectorPrimaryFocus` prop on `<ModalWrapper>` in order to pass it through to `<Modal>` for configuration
**New**
- add `selectorPrimaryFocus` prop on `<ModalWrapper>`
**Changed**
- updated Storybook examples
=>  fix(ModalWrapper): pass `selectorPrimaryFocus` prop through to `<Modal>`

src/components/ComposedModal/ComposedModal-story.js, src/components/ComposedModal/ComposedModal-test.js, src/components/ComposedModal/ComposedModal.js, src/components/ComposedModal/__snapshots__/ComposedModal-test.js.snap, src/components/Modal/Modal.js
Closes IBM/carbon-components-react#1623
This PR adds support for the `selectorPrimaryFocus` prop on `<ComposedModal>` to match `<Modal>` and `<ModalWrapper>`
Related: #980 #1124 #1621 #1633
**New**
- focus management methods (many shared with `<Modal>`)
- pass ref for primary focusable element to `<ComposedModal>`s using `<ModalFooter>`
- storybook example `<ComposedModal>` with trigger button
**Changed**
- declare `<Modal>` methods before they are called
=> feat(ComposedModal): support selectorPrimaryFocus prop

src/components/Accordion/Accordion.js, src/components/AccordionItem/AccordionItem.js
Closes IBM/carbon-components-react#1650
This PR uses a more appropriate `role` for `<AccordionItem>`s with respect to our current markup and includes the `aria-expanded` on the component. This change is meant to support screen readers but exposes a potential larger issue with the elements used to construct our `<Accordion>`s
**Changed**
- use `tab` role for `<AccordionItem>` to correspond with the `role` on `<Accordion>`
- tie `aria-expanded` state to component open/closed state
=> fix(AccordionItem): add aria-expanded and use tab role

src/components/ModalWrapper/ModalWrapper-story.js, src/components/ModalWrapper/ModalWrapper.js, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
This PR will add icon option to the trigger button of ModalWrapper.
In the Story, I used the same select of icons, which is in the Button-Story.
=> feat(ModalWrapper): add icon option to trigger button

src/components/Checkbox/Checkbox-story.js
Closes IBM/carbon-components-react#1670
This PR will deduplicate the `id`s for the example `<Checkbox />` components in storybook
**Changed**
- component `id`s in `<Checkbox />` storybook example
=> docs(Checkbox): remove duplicate id from `checked` story

package.json, src/components/CopyButton/CopyButton.js
Closes IBM/carbon-components-react#1673
This PR will add the new experimental CopyButton changes
=> feat(CopyButton): support new icon strategy

src/components/AccordionItem/AccordionItem-test.js, src/components/AccordionItem/AccordionItem.js
Closes IBM/carbon-components-react#1660
This PR adds support for closing an open `AccordionItem` with the `Esc` key. The current keypress handler also does not trigger the opening and closing of `AccordionItem`s. Due to that behavior already being native to button elements, it does not look like we need to handle space bar and Enter key presses separately.
**Changed**
- listen to `onKeyDown` event rather than `onKeyPress` to support `Esc` key
**Removed**
- listeners for space bar and enter key
=> feat(Accordion): close accordion item on Esc keypress

src/components/Toggle/Toggle-story.js, src/components/Toggle/Toggle.js, src/components/ToggleSmall/ToggleSmall-story.js, src/components/ToggleSmall/ToggleSmall.js
Closes IBM/carbon-components-react#1692
This PR will add the new experimental toggle and small toggle changes
currently blocked by sketch license expiring and being unable to check sketch file for whether or not `<ToggleSmall>` maintains the check mark SVG in the experimental version
=> feat(Toggle): add experimental toggle

src/components/Tooltip/Tooltip-story.js, src/components/Tooltip/Tooltip.js, src/components/TooltipIcon/TooltipIcon-story.js
Closes IBM/carbon-components-react#1707
This PR will support the new icon strategy in the experimental tooltip (related: https://github.com/IBM/carbon-elements/issues/228, https://github.com/IBM/carbon-elements/pull/231)
=> feat(Tooltip): add experimental tooltip

src/components/Tag/Tag-story.js, src/components/Tag/Tag-test.js, src/components/Tag/Tag.js
Closes IBM/carbon-components-react#1720
This PR removes some boolean logic which was preventing the `children` of the `<Tag>` component from rendering when it was a falsey value like `0`. It appears like initially the logic was implemented to always render a value, but since `props.children` is not a required prop, it should be fine to have nothing render if no children are passed into the `<Tag>`
alternatively, we can set a default value on `children` rather than displaying the `type` value by default, which may cause problems when users migrate from v9 to v10 too since the type values are changing
=> fix(Tag): remove boolean logic from rendering children

src/components/DatePicker/DatePicker.js, src/components/DatePickerInput/DatePickerInput.js
The vanilla experimental date picker is displaying the SVG icons as a background image. To match this approach, we can avoid using the `<Icon>` component in the React DatePicker
**Changed**
- conditionally render `<Icon>` based on feature flag state
=> fix(DatePicker): avoid rendering extra icons for experimental DatePicker

src/components/Tabs/Tabs.js
Closes IBM/carbon-components-react#1648
This PR adds the experimental tabs component
=> feat(Tabs): use experimental icons

src/components/DropdownV2/DropdownV2-story.js, src/components/DropdownV2/DropdownV2-test.js, src/components/DropdownV2/DropdownV2.js, src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap
Closes IBM/carbon-components-react#1706
This PR adds optional props to `DropdownV2` for a title and helper text.
**New**
- optional `titleText` and `helperText` props
=> feat(DropdownV2): support title and helper text options

src/components/Modal/Modal.js
Closes IBM/carbon-components-react#1751
This PR avoids a NPE in `<Modal />` by performing a null check on the focus button before chaining the `.querySelector` method
=> fix(Modal): avoid NPE with null check

src/internal/FloatingMenu.js
> Note: this PR is against v5 branch
scrollY is not available in IE but pageYOffset is an alias. The 6.x.x floating menu uses pageYOffset
=> fix(FloatingMenu): changes scrollY to pageYOffset for IE

src/components/OverflowMenu/README.md
**New**
- `README.md` for overflow menu, highlighting `floatingMenu` and `primaryFocus` React props
=> docs(OverflowMenu): highlight floatingMenu and primaryFocus

src/components/RadioButtonGroup/RadioButtonGroup-test.js, src/components/RadioButtonGroup/RadioButtonGroup.js
Currently, if a classname is provided to `<RadioButtonGroup>` it overwrites the base `${prefix}--radio-button-group` classname.
This PR adds the fix where a provided class will merge with the base class.
=> fix(radiobuttongroup): custom class should merge with base class

src/components/ListBox/ListBoxMenuIcon.js, src/components/MultiSelect/MultiSelect-story.js, src/components/MultiSelect/MultiSelect.js, src/components/MultiSelect/__tests__/__snapshots__/MultiSelect-test.js.snap
Closes IBM/carbon-components-react#1801
This PR will add support for translatable SVG titles in `<ListBox />`
**New**
- `listBoxMenuIconTranslationIds` prop, which takes an object with `close.menu` and `open.menu` properties
**Changed**
- return SVG `<title>` if `description` prop is truthy for experimental `ListBoxMenuIcon`
=> feat(ListBoxMenuIcon): support translatable SVG icon title

src/components/Notification/Notification.js
Closes IBM/carbon-components-react#1831
This PR removes `children` from `propTypes` to prevent it from being listed in our documentation, since it is not used at all
=> refactor(Notification): remove unused props

src/components/Tooltip/Tooltip-test.js, src/components/Tooltip/Tooltip.js
Changes the Tooltip trigger element to be `<button>` instead of a `<div>` element per #1494 
**Changed**
- Change `<div>` elements to `<button>` elements.
- On the Tooltip variation with Icon, the icon container element now needs the style reset that comes with the `prefix + '--tooltip__trigger'` classname.
- Moved the `role="tooltip"` attribute to the tooltip container element.
=> chore: Update wai-aria on tooltip. resolve #1494

examples/create-react-app/package.json
This PR bumps the `webpack-dev-server` version in the `create-react-app` example `package.json` to avoid a security vulnerability in an old version of the package and remove GitHub's vulnerability warning
Alternatively, we can probably just dismiss the warning because this code is not actually used outside of example environments
=> chore: bump webpack-dev-server in example package.json

src/internal/InnerClickListener.js, src/internal/__tests__/InnerClickListener-test.js
Update InnerClickListener as the current implementation does not work if elements disappear from the DOM; if an element is clicked and it goes away such as a toggle open/close icon switching states, it should not trigger an onClickOutside event
**New**
- added test case for InnerClickListener-test
**Changed**
- check if event target exists in DOM
=> Update 'InnerClickListener' 

src/components/MultiSelect/MultiSelect.js
Closes IBM/carbon-components-react#[1847](https://github.com/IBM/carbon-components-react/issues/1847)
* `translateWithId` is optional field. And hence we are not defining this prop parameter in code.
* But we see Warning: Failed prop type: MultiSelect: prop type `translateWithId` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
**Changed**
- src/components/MultiSelect/MultiSelect.js
=> fix(MultiSelect): fixed translateWithId prop-type, resolves #1847

src/components/Notification/Notification-story.js, src/components/Notification/Notification.js
Closes IBM/carbon-components-react#1834
This PR adds support for the `children` prop so that users can compose their own notification content
**New**
- `children` prop for `<NotificationTextDetails>` which is passed through from `<ToastNotification>` or `<InlineNotification>`
**Changed**
- support experimental close icon
=> feat(Notification): allow composable notification content

src/components/UIShell/SideNav.js, src/components/UIShell/__tests__/__snapshots__/SideNav-test.js.snap
Elements having a WAI-ARIA complementary role such as `<aside>` used in our sidenav must have a label specified with aria-label.
This PR gives the `<aside>` element in the sidenav an `aria-label="side navigation"` silencing the error thrown by our automated test and providing a more adequate description for our users.
=> fix(ui-shell): add aria label to sidenav with complimentary landmark

src/components/Tabs/Tabs-story.js, src/components/Tabs/Tabs-test.js, src/components/Tabs/Tabs.js
Closes IBM/carbon-components-react#1854
Related:
#1790
#1784
#1846
This PR exposes a `tabContentClassName` prop for the consumer to attach custom classNames to the tab content container element
=> feat(Tabs): allow custom className for `<TabContent>`

src/components/Modal/Modal.js
Uses the secondary button for danger modals in componentsX, [as seen here](https://next.carbondesignsystem.com/components/modal/code).
**Changed**
- Uses tertiary button only for non-componentsX component
=> fix(modal): uses secondary button on danger modal for componentsX

src/components/DataTableSkeleton/DataTableSkeleton-story.js, src/components/DataTableSkeleton/DataTableSkeleton-test.js, src/components/DataTableSkeleton/DataTableSkeleton.js
Most of the time we have headers already in place while loading the table data, so why not to display them? This prop is optional and looks really cool when passed to the component.
**New**
- optional headers prop
=> feat(DataTableSkeleton): add optional headers property

src/components/Tile/Tile-story.js
Noticed a small typo in the `Tiles` story.
**Changed**
- typo -- changed `clicable` to `clickable`
=> fix(Tile): typo in clickable variation knob desc

src/components/Tooltip/Tooltip-story.js, src/components/Tooltip/Tooltip.js, src/internal/FeatureFlags.js
Fixes #1864.
**New**
- Deprecation warning for `clickToOpen=false` in `<Tooltip>`.
- Default prop for `clickToOpen`, `true` is set there for `v10`.
=> chore(Tooltip): deprecate non-click-to-open in regular tooltip

src/components/OverflowMenu/OverflowMenu.js
Closes #1877 
Include `iconProps` when rendering the Carbon X icon version.
**NOTE:** My understanding was that it made sense to include icon props to this icon, but let me know if you want certain props or just the classNames here 🤔 
With this change, you start to get some expected props...
**Changed**
- add `iconProps` to Carbon X `OverflowMenu` icon
=> fix(overflowMenu): include iconProps for CarbonX version

src/components/Modal/Modal.js
Closes IBM/carbon-components-react#1880
This PR adds a null pointer exception check for the primary focusable button ref
=> fix(Modal): NPE check for focusable element ref

src/components/DropdownV2/DropdownV2.js
Closes IBM/carbon-components-react#1898
=> fix(DropdownV2): uses strict equality operator to know if item is highlighted, resolves #1898

src/components/ToggleSmall/ToggleSmall-story.js, src/components/ToggleSmall/ToggleSmall.js
Closes IBM/carbon-components-react#1901
also removes unused props from component story
=> fix(ToggleSmall): replace `class` prop with `className`

src/components/OverflowMenu/OverflowMenu.js, src/components/Toolbar/Toolbar-story.js
Closes IBM/carbon-components-react#1885
This PR adds a check in the click handler method to make sure that the menu body does not exist or that the event target is not propagating from the current menu body before modifying the menu state and firing the `onChange` handler
=> fix(OverflowMenu): check menu body and click handler event origin

src/components/DatePickerInput/DatePickerInput.js
Closes #1904 
In the current Carbon X design kit, the calendar icon should be displayed for all calendar variations *except* for the `simple` type.
`DatePickerInput` controls logic for displaying the icon in Carbon X, but the following prevents the icon for rendering for the `range` type:
```javascript
if (datePickerType !== 'single') {
return;
}
```
This PR proposes 2 updates to this logic to both maintain the current logic for existing Carbon `DatePicker`s and also add an extra if-statement to make sure the Carbon X version gets the right icons for the right types.
**Changed**
- update icon render logic in `DatePickerInput` to match Carbon X design spec
=> fix(DatePickerInput): update logic for displaying icon for CarbonX

src/components/Button/Button-story.js
Closes IBM/carbon-components-react#1909
This PR adds support for configuring button examples that use custom root nodes
=> docs(Button): add example with custom link component as root

src/components/ModalWrapper/ModalWrapper-story.js
Fixes #640.
**New**
- A knob for `danger` in `<ModalWrapper>` story
=> chore(Storybook): add knob for danger in ModalWrapper

src/components/Button/Button.js, src/components/Checkbox/Checkbox.js, src/components/InlineCheckbox/InlineCheckbox.js, src/components/NumberInput/NumberInput.js, src/components/RadioButton/RadioButton.js, src/components/Select/Select.js, src/components/TextInput/TextInput.js, src/tools/__tests__/mergeRefs-test.js, src/tools/mergeRefs.js
Refs #1191, #1777.
**New**
- Supports `ref` for `<Button>`, `<InlineCheckbox>`, `<NumberInput>` and `<RadioButton>`.
=> feat(components): support forwardRef for button and stateful

package.json
I noticed that a typo made it in for a propType on a previous PR.
Someone added PropTypes.function instead of PropTypes.func.
This change adds the linting for react/no-typos that would catch this typo plus a few others.
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-typos.md
package.json - Simply added no-typos to the eslintConfig as an error. 
The types of things it catches should be considered errors.
I tested by converting the PropType in DatePicker to be function:
```
/**
* The `change` event handler.
*/
onChange: PropTypes.function,
```
It properly spits out:
```
git\carbon-components-react\src\components\DatePicker\DatePicker.js
206:25  error  Typo in declared prop type: function  react/no-typos
```
=> chore(lint): Add no-typos for react linting

src/components/CodeSnippet/CodeSnippet-story.js
Closes IBM/carbon-components-react#2041
**Changed**
- add padding inline to storybook to differentiate between skeleton states.
- added padding in single line at the end 
Related: https://github.com/IBM/carbon-components/pull/2169
=> chore(code-snippet): add margin to seperate skeletons

src/components/Slider/Slider.js
Closes IBM/carbon-components-react#2082
`<TextInput>` (and several other form components) include the `<FormItem>` wrapper out of the box. This PR replaces `<TextInput>` in the `<Slider>` component with native text inputs so that `<Form>` styles are not applied.
Related: https://github.com/IBM/carbon-components-react/issues/1681
=> refactor(Slider): replace Carbon TextInput

.github/ISSUE_TEMPLATE/accessibility-issue--.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md
Closes IBM/carbon-components-react#2098
Our issue templates were not properly formatted and caused all CI builds to fail. This PR formats them to pass CI
=> chore: format GitHub issue templates and update snapshots

docs/migration/migrate-to-7.x.md, src/components/DatePicker/DatePicker.js, src/components/DatePicker/migrate-to-7.x.md, src/components/OverflowMenu/migrate-to-7.x.md, src/components/OverflowMenuItem/migrate-to-10.x.md, src/components/OverflowMenuItem/migrate-to-7.x.md, src/components/RadioButton/migrate-to-7.x.md, src/components/Slider/migrate-to-7.x.md, src/components/Tag/migrate-to-7.x.md, src/components/Tooltip/migrate-to-7.x.md
Refs #2100.
Refs #1759.
**New**
- `migrate-to-7.x.md` for `<DatePicker>`, `<Slider>`, `<Tag>`
**Changed**
- Root migration guide to link to the additions/changes.
- `migrate-to-7.x.md` in `<OverflowMenu>`, to cover change in `ref` behavior.
- `migrate-to-7.x.md` in `<OverflowMenuItem>`, the file name and made it a bit clearer.
- `migrate-to-7.x.md` in `<Tooltip>`, to cover change in `ref` behavior.
=> docs(migration): misc updates

src/components/Icon/Icon.js
Refs #2100.
Aligns the actual behavior to that doc update.
**Removed**
- `name` prop in `<Icon>` (for `v10`)
=> chore(Icon): remove name prop for v10

src/components/Search/Search-story.js, src/components/Search/Search.js
Closes IBM/carbon-components-react#2120
This PR removes the `value` storybook knob for `<Search>` and replaces it with `defaultValue` (consistent with our `<TextInput>` story)
**Changed**
- `<Search>` storybook knobs
- `<Search>` prop types
=> docs(Search): make input value editable

src/components/DataTable/TableSelectRow.js, src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/RadioButton/RadioButton-test.js, src/components/RadioButton/RadioButton.js, src/components/RadioTile/RadioTile-test.js
apply correct aria label prop for radio select on data table. resolving the dev warning about `Invalid ARIA attribute`
**Changed**
- apply correct aria label prop for radio select on data table.
=> fix: apply correct aria label prop for radio

src/components/ModalWrapper/ModalWrapper-story.js
Closes IBM/carbon-components-react#2143
This PR makes the `value` attribute of each radio button in the `<ModalWrapper>` input modal example unique to avoid unexpected behavior when interacting with the form controls.
=> docs(ModalWrapper): use unique radio button values

src/components/MultiSelect/FilterableMultiSelect.js
Fixes #2162.
**New**
- `translateWithId` prop to `<MultiSelect.Filterable>`.
=> fix(multi-select): introduce translateWithId

src/components/OverflowMenu/OverflowMenu-test.js, src/components/OverflowMenu/OverflowMenu.js
Added a new property, `menuOptionsClass`, to `overflowMenu`. This allows a class to be specified on the `overflowMenu` options. This is particularly useful when `floatingMenu` is set, as the menu is appended to the body and has no obvious selector.
**Changed**
- Changed `overflowMenu` to accept a new property `menuOptionsClass` and pass it down to the menu body.
=> feat(OverflowMenu): add menuOptionsClass to overflowMenu

src/components/DataTableSkeleton/DataTableSkeleton.js
Closes IBM/carbon-components-react#1963
Right now the `headers` prop for the `DataTableSkeleton` can only be an array of strings, whereas the `headers` prop for the `DataTable` is required to be an array of objects.
This change will allow the `DataTableSkeleton` to accept an array of strings (so as not to break existing usage) and an array of objects (to match `DataTable` and resolve #1963).
**Changed**
- `headers` prop for `DataTableSkeleton` can now accept array of objects as well
- if you pass `headers` as an array of objects to `DataTableSkeleton`, it will create a new array of "normalized" headers (just an array of strings) to match existing component structure
=> fix(DataTableSkeleton): headers prop can now be array of objects to match DataTable

.circleci/config.yml
Re-enable CI deployment for React storybook. This should be merged in after a v6 route is setup.
TODO
=> chore(ci): re-enable storybook, remove experimental

src/components/Modal/Modal.js, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
This is a backport of: #2141 and #2163 for v6.
=> fix(modal): backport onTransitionEnd NPE and modal focus fixes to v6

src/components/Loading/Loading.js
🌏 👋  hello you all 
Closes https://github.com/IBM/carbon-components-react/issues/2191
Adds property `description` which is added as `aria-label` to the loading indicators (both inline and normal). This way VO will now announce the loading state.
Tested locally with iOS and VO. Reader will now announce that a loader is on the screen.
**New**
Property `description` which is added as `aria-label` to the `Loading` component.
=> fix(Loading): adds aria-label and description property to component

src/components/ComposedModal/ComposedModal-test.js, src/components/ComposedModal/ComposedModal.js, src/components/Modal/Modal-test.js, src/components/Modal/Modal.js
Fixes #2249.
**Changed**
- Changed the primary button of danger mode from `danger--primary` to `danger`
=> fix(Modal): fix button type in danger mode

src/components/Notification/Notification.js
closes #2246 
adds aria-label to close button on toast notification so that the button's purpose can be known to screen reader users.
- adds `aria-label={iconDescription}` to the `<button>` component
=> fix(notification): adds aria-label to button

src/components/AccordionItem/AccordionItem.js
closes #2251 
Removes the invalid role attribute from AccordionItem component since the role was causing an Axe error.
- remove `role=presentation` from AccordionItem's `<li>` element.
=> fix(accordion): remove role=presentation

src/components/NumberInput/NumberInput.js
Hello you all and happy Tuesday morning! ☀️ 🌸 
Closes https://github.com/IBM/carbon-components-react/issues/2188
As discussed in https://github.com/IBM/carbon-components-react/issues/2188, the issue seems to be that the label element is present, but it is empty and hidden. Adding a label on the `input` element should fix that a11y violation.
**New**
adds aria-label property on `input` element
**Changed**
- `src/components/NumberInput/NumberInput.js`
=> fix(InputField) -  adds aria-label property on `input` element

src/components/DataTable/README.md
The documentation for the `DataTable` expansion components seems to be out of date or misaligned with what I needed to get it to work. In order to get it to work properly, I had to remove the `TableCell` component from inside `TableExpandedRow` and set the `colSpan` property of `TableExpandedRow` to `headers.length + 1`
**Changed**
- Update to reflect that no `TableCell` should be a child of `TableExpandedRow`
- Update to add `colSpan` property to the `TableExpandedRow` element
**Removed**
- Removed `TableCell` from being a child of `TableExpandedRow` in the `DataTable` expansion docs
=> docs(DataTable): Update documentation for DataTable expansion

src/components/Button/Button.js, src/components/Checkbox/Checkbox.js, src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableBatchAction-test.js.snap, src/components/DataTable/__tests__/__snapshots__/TableBatchActions-test.js.snap, src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap, src/components/Select/Select.js, src/components/TextInput/TextInput.js, src/components/UIShell/HeaderMenuItem.js, src/components/UIShell/Link.js, src/components/UIShell/SideNavMenuItem.js, src/components/UIShell/SideNavSwitcher.js, src/components/UIShell/__tests__/__snapshots__/HeaderMenu-test.js.snap, src/components/UIShell/__tests__/__snapshots__/HeaderMenuItem-test.js.snap, src/components/UIShell/__tests__/__snapshots__/SideNavMenuItem-test.js.snap, src/components/UIShell/__tests__/__snapshots__/SideNavSwitcher-test.js.snap
This change updates React component name for various forward-ref'ed components from just `<ForwardRef>` to  something like `<ForwardRef(TextInput)>`.
Refs #1768.
**Changed**
- Change the 1st arg of `React.forwardRef()` of various components to named functions.
Please use "Diff settings" - "Hide whitespace changes" for reviewing.
=> chore(components): better name with forwardRef

src/components/Pagination/Pagination-test.js, src/components/Pagination/Pagination.js
Closes IBM/carbon-components-react#2264
Pagination component with `pageInputDisabled: true` prop would display forward and backward buttons as disabled, while they'd still work when clicking.
This PR disables check for `pageInputDisabled` so the buttons' styling is not affected by it.
`disabled` prop disables next/previous page buttons so it can be used in parallel with `pageInputDisabled` if that functionality is needed.
=> fix(Pagination): pageInputDisabled won't append disabled class to buttons

src/components/DropdownV2/DropdownV2.js
related to https://github.com/carbon-design-system/carbon-components-react/issues/1952
copied from https://github.com/carbon-design-system/carbon-components-react/pull/2293
=> fix(DropdownV2): v5 - passes through translation to menu icon

.github/stale.yml
After this runs once (should be within 24 hours after merge), and in a few days when issues close, we can add exemption labels.
=> Add stalebot. Update exemptions after it runs once

src/components/DropdownV2/DropdownV2.js
*against v6 branch
so consumers of dropdownv2 can specify translations for title text of the icon
Related to https://github.com/carbon-design-system/carbon-components-react/issues/1952
updated version of my previous pr, i noticed that FilterableMultiSelect has a directly analogous instance of this so I figured I would just copy that pattern instead of making a new one.
=> fix(DropdownV2): v6 - explicitly passes through translateWithId to menu icon

src/components/UIShell/SideNavHeader.js, src/components/UIShell/SideNavLink.js, src/components/UIShell/SideNavMenu.js, src/components/UIShell/UIShell-story.js, src/components/UIShell/__tests__/SideNavHeader-test.js, src/components/UIShell/__tests__/SideNavMenu-test.js, src/components/UIShell/__tests__/__snapshots__/SideNavHeader-test.js.snap, src/components/UIShell/__tests__/__snapshots__/SideNavLink-test.js.snap, src/components/UIShell/__tests__/__snapshots__/SideNavMenu-test.js.snap
Fixes #2008.
**Changed**
- Changed `icon` API taking React node to `renderIcon` API taking React component class, for UI shell components. It aligns to other components in this library.
=> chore(SideNav): align icon API to other components

src/components/ComposedModal/ComposedModal.js, src/components/Modal/Modal.js
Fixes carbon-design-system/carbon-components#629 - To see if the issue is merely requesting for changing prop types.
**Changed**
- Prop types for modal heading/label to `PropTypes.node`.
=> fix(Modal): accept nodes to heading

src/components/Button/Button-test.js, src/components/Button/Button.js, src/components/Tooltip/Tooltip.js
Refs carbon-design-system/carbon-components#2308.
**Removed**
- `icon` prop refs in `<Button>` and `<Tooltip>`.
=> chore(components): complete removing icon prop

src/components/OverflowMenu/OverflowMenu-story.js
Closes https://github.com/carbon-design-system/carbon-components/issues/2248
Related to https://github.com/carbon-design-system/carbon-components/pull/2379
Removes an incorrect example of having an `Add +` button in an `OverflowMenu`
=> fix(overflow-menu): remove add from menu

src/components/MultiSelect/MultiSelect.js, src/components/MultiSelect/__tests__/MultiSelect-test.js
This is integrating work in a fix on v6 to v5. Same bugfix was released in v6 as the following issue https://github.com/carbon-design-system/carbon-components-react/pull/1021/files#diff-d5a233582a5bb13fa38d69fe8692b324. The one discrepency between that fix and this is I combined the if conditions.
@marijohannessen noticed you merged the v6 fix for this issue, if you could give this a review would appreciate
**Changed**
- {{MultiSelect handleOnToggleMenu method and related tests}}
=> fix(MultiSelect): close MultiSelect after any option is selected/unselected

.github/ISSUE_TEMPLATE/accessibility-issue--.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request-or-enhancement---.md, .github/ISSUE_TEMPLATE/question.md
Closes IBM/carbon-components-react#2345
Runs prettier on the repo to avoid CI errors
=> chore: prettier

src/components/OverflowMenu/README.md
Closes #1924.
**New**
- `README.md` content for `<OverflowMenu>` mentioning that the `children` has to accept `ref`.
=> docs(OverflowMenu): note on children

package.json
Turns out the latest version is actually [5.53.0](https://www.npmjs.com/package/carbon-components-react/v/5.53.0), so this is bumping on the latest version 👍 This also adds in a `publishConfig.tag` config to prevent accidentally publishing to latest.
=>  chore(release): v5.53.1

src/components/TileGroup/TileGroup.js
Closes IBM/carbon-components-react#2358
Adds the legend attribute to the TileGroup if it was set by the calling code.
=> fix: added the legend to TileGroup, resolves #2358

src/components/TileGroup/TileGroup.js
Cherry picked the fix from https://github.com/carbon-design-system/carbon-components-react/pull/2359 to the `v6` branch
=> feat(tile-group): add legend to TileGroup, resolves #2358 (#2359)

package.json
Publish v6.115.0
**New**
**Changed**
- `package.json` now has `publishConfig.tag` set to `6.x`
**Removed**
=> chore(release): publish v6.115.0

src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap, src/components/ListBox/ListBox.js, src/components/ListBox/__tests__/ListBox-test.js, src/components/ListBox/__tests__/__snapshots__/ListBox-test.js.snap, src/components/MultiSelect/__tests__/__snapshots__/MultiSelect-test.js.snap
Closes #2373 
Closes #2374 
Closes #2375 
This PR removes the default listbox inner tabindex value by default
For the testers:
ensure that no extra tab stops exist when navigating the list box components (multiselect, filterable multiselect, dropdownv2, combobox)
=> fix(ListBox): remove default inner tab index

src/components/OverflowMenu/OverflowMenu-test.js, src/components/OverflowMenu/OverflowMenu.js
Added a new property, `menuOptionsClass`, to `<OverflowMenu>`. This allows a class to be specified on the `<OverflowMenu>` props. This is particularly useful when `floatingMenu` is set, as the menu is appended to `<body>` and has no obvious selector. Fixes https://github.com/carbon-design-system/carbon/issues/2876.
This is a backport of #2174 from `carbon-components-react@7` to `carbon-components-react@6`.
I apologise for ignoring the comment saying that this PR should be opened against [https://github.com/carbon-design-system/carbon](https://github.com/carbon-design-system/carbon), but since I wasn't able to find any React components in [the `v9` tree](https://github.com/carbon-design-system/carbon/tree/v9) over there, I believe the old versions have not been ported over there, and the …
=> feat: add menuOptionsClass to overflowMenu

src/components/ComposedModal/ComposedModal.js, src/components/ComposedModal/__snapshots__/ComposedModal-test.js.snap
Issue:
- Current modal component has a accessibility checkpoint violation. `All content must reside within a WAI-ARIA landmark or labelled region role`
- The role "presentation" in the modal is not a WAI-ARIA role.
Details in: https://aat.w3ibm.mybluemix.net/token/98e2765a-de76-49d2-9f5c-605778089422/b7118222-21ab-441d-9037-25deacdefdf0/archives/2018AugustDeploy/doc/w3/help/en-US/idhi_accessibility_check_g1157.html
Solution:
- adding prop that allow modification of the role of the container so no more violation in the content of the modal
=> fix(Modal): allow differnt roles for modal

package.json
fix `npm publish` outdated module issues and release v6.115.4
=> chore(release): v6.115.4

src/components/MultiSelect/FilterableMultiSelect.js
- MultiSelect.Filterable doesn’t support `useTitleInItem` (tooltip on hover) #2328
- https://github.com/carbon-design-system/carbon-components-react/issues/2328
Ref: https://github.com/carbon-design-system/carbon-components-react/pull/2330
=> Add support for useTitleInItem (tooltip on hover) for carbon 9 (v6)

src/components/TextArea/TextArea.js
I've added ref forwarding to the TextArea component the same way it's done in the TextInput component.
=> fix(TextArea): add ref forwarding to TextArea

src/components/DropdownV2/DropdownV2-test.js, src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap, src/components/ListBox/ListBoxField.js, src/components/ListBox/__tests__/ListBoxField-test.js, src/components/ListBox/__tests__/__snapshots__/ListBox-test.js.snap, src/components/ListBox/__tests__/__snapshots__/ListBoxField-test.js.snap, src/components/MultiSelect/__tests__/__snapshots__/FilterableMultiSelect-test.js.snap, src/components/MultiSelect/__tests__/__snapshots__/MultiSelect-test.js.snap
Closes https://github.com/carbon-design-system/carbon/issues/3481
This PR addresses a couple of DAP violations in the listbox components
**Changed**
- add `aria-owns` and `aria-controls` attributes only when the referenced element is rendered
Ensure the listbox components pass a11y testing
=> fix(ListBox.Field): set aria-owns and aria-controls

src/components/Tile/Tile-story.js, src/components/Tile/Tile.js
Closes https://github.com/carbon-design-system/carbon/issues/3537
ref: https://github.com/carbon-design-system/carbon/issues/2959 https://github.com/carbon-design-system/carbon/pull/3431
This PR removes console warnings created by invalid props and invalid prop types in the `<SelectableTile>`
Ensure no console errors are emitted when viewing the component
=> fix(SelectableTile): remove console warnings

src/components/Button/Button.Skeleton.js
Closes https://github.com/carbon-design-system/carbon/issues/2958
Use `div` instead of `button` in `ButtonSkeleton` to fix a11y issues. Since the button is normally labeled via text, and the skeleton button has no text, it throws an error. Using a `div` alleviates this issue.
=> fix(button): use div for skeleton button

src/components/Tile/Tile-test.js, src/components/Tile/Tile.js
closes https://github.com/carbon-design-system/carbon/issues/3829
add `persist` to persist the event object so it can be used in async.
- added `persist()` on event.
Testing / Reviewing
make sure we can see the event properties in the handlerKeyDown and handlerClick props on the component
=> fix(Tile): persist event object

src/components/MultiSelect/MultiSelect-story.js, src/components/MultiSelect/MultiSelect.js
Porting over this change from v7.X over to 6.X [3395](https://github.com/carbon-design-system/carbon/pull/3395) which closed [#3393](https://github.com/carbon-design-system/carbon/issues/3393)
This **PR** passes ```translateWithId``` through to the nested ```<ListBox.Selection>``` in MultiSelect components
**Testing / Reviewing**
Ensure that translations are working correctly for the <ListBox.Selection> title
=> feat(MultiSelect): pass through  translations (cherry-pick from v7)

src/components/AccordionItem/AccordionItem.js, src/tools/key.js
In `AccordionItem`, it is calling the `key.match` utility with wrong parameters. Based on the example given in https://github.com/carbon-design-system/carbon-components-react/blob/master/src/tools/key.js#L72, it should pass the entire `evt` object instead. This is now causing an NPE thrown.
```
Uncaught TypeError: Cannot read property 'which' of undefined
at match (key.js?13e0:63)
at eval (AccordionItem.js?33e3:86)
at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:347)
at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:397)
at invokeGuardedCallback (react-dom.development.js?61bb:454)
at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?61bb:468)
at executeDispatch (react-dom.development.js?61bb:600)
at executeDispatchesInOrder …
```
=> fix(AccordionItem): fix NPE thrown by key.match

src/components/DataTable/README.md
- Unnecessary `{` causing linting error.
=> docs: unnecessary curly brace
