package.json

ibm/aat is not a public dependency, remove this for now

fix(dependencies): remove ibma/aat dependency

---

index.js
package.json

AppContainer was removed but not from the index file. That is removed now as well.

fix(app): remove app container

---

.travis.yml
package.json

enable semantic release, turn off deploy script

chore(release): turn on semantic release

---

package.json

Fixes the build - build step wasn't running before publish

fix(build): add pre-publish build

---

.storybook/components/PaginationStory.js
components/ModuleHeader.js
components/ModulesContainer.js
components/Notification.js
components/NumberInput.js
components/OrderedList.js
components/OverflowMenu.js
components/OverflowMenuItem.js
components/Pagination.js
components/ProgressIndicator.js
components/RadioButton.js
components/RadioButtonGroup.js
components/Search.js
components/Select.js
components/SelectItem.js
components/SelectItemGroup.js
components/Table.js
components/Tabs.js
components/Tag.js
components/TextArea.js
components/TextInput.js
components/Toggle.js
components/Tooltip.js
components/UnorderedList.js

To render a pagination component when the total pages is unknown, pass down `unknownPages: true` to the `pagination` component.
```jsx
<Pagination unknownPages={true} />
```

Pagination update

---

.storybook/components/SelectStory.js
components/Select.js
components/__tests__/Select-test.js

Reopening https://github.com/carbon-design-system/carbon-components-react/pull/11 to point at master

Inline select

---

package.json

Remove an out of date ref to addon-info

chore: remove old dep

---

CONTRIBUTING.md
components/DetailPageHeader.js
components/InteriorLeftNav.js
components/__tests__/Loading-test.js
internal/FloatingMenu.js
internal/OptimizedResize.js
package.json
yarn.lock

* Added `window-or-global` to the `devDependencies`
* Use `import window from 'window-or-global` in every file that requires accessing the `window` object
* 🎨 Updated `CONTRIBUTING.md` with links to this repository instead of the GHE repo.

Fixes server-side rendering

---

README.md

Add the Travis status icon to tell at a glance if the 
tests are passing

docs: add travis status

---

.travis.yml

Add the test run script to travis to verify PRs and pushes

test(travis.yml): run tests on Travis

---

index.js

The index.js export was missing a couple components / exporting the FileUploader incorrectly

fix(index): was missing a couple components

---

.storybook/components/DatePickerStory.js
components/DatePicker.js
components/DatePickerInput.js
components/__tests__/DatePicker-test.js
package.json
yarn.lock

Added the new date picker component consisting of `DatePicker` and `DatePickerInput`.
**There are 3 different types:**
1. Simple Date Picker (one input field without a calendar)
2. Single Date Picker (one input field with a calendar)
3. Range Date Picker (two input fields with a calendar)
The Date Picker is built on top of [Flatpickr](https://github.com/chmln/flatpickr).

feat(date-picker): added date picker component

---

.storybook/components/AccordionStory.js
components/AccordionItem.js
components/__tests__/AccordionItem-test.js

Closes https://github.com/carbon-design-system/carbon-components-react/issues/61

fix(accordionItem): allow accordionItem to update on prop change

---

.storybook/components/TimePickerStory.js
components/TimePicker.js
components/TimePickerSelect.js
components/__tests__/Text.js
components/__tests__/TimePicker-test.js
index.js

Added the new Time Picker component consisting of `TimePicker` and `TimePickerSelect`.

feat(time-picker): added time picker component

---

components/Toolbar.js
components/__tests__/Toolbar-test.js
index.js

A few elements were not being exported. This fixes that.
- Exports `Toolbar` and `DatePicker` and all subcomponents

fix(index): export tooltip, datepicker

---

index.js

The ToolbarSearch had the incorrect path to the component

fix(index): update path to ToolbarSearch

---

components/Pagination.js
components/__tests__/Pagination-test.js

Resurrects this feature: https://github.ibm.com/Bluemix/bluemix-components-react/pull/537

fix(pageSize): add pageSize prop back in

---

components/OverflowMenu.js
components/OverflowMenuItem.js
components/__tests__/OverflowMenu-test.js

Whoops! Thought just removing the blur would fix the IE11 bug - but nope, needs the rest of the old fix as well.

fix(overflowmenu): bring over the rest of the IE11 fix

---

components/Pagination.js
package.json

- enable "items per page" when `pagesUnknown` is `true`
- add new prop `pageInputDisabled`
- externalize some i18n strings
- fix some console exceptions

feat(pagination): items per page when pages unknown, pageInputDisabled prop, i18n

---

components/AccordionItem.js

fix(AccordionItem): add title prop to defaultProps (il8n)

---

components/Switch.js

fix(Switch): add text to defaultProps (i8ln)

---

components/Checkbox.js

fix(Checkbox): add defaultProps for text strings (i8ln)

---

components/Button.js
components/CopyButton.js

fix(Button): add iconDescription as defaultProp (i8ln)

---

components/DatePicker.js
components/DetailPageHeader.js
components/TableBody.js
yarn.lock

This resolves
- https://github.com/carbon-design-system/carbon-components-react/issues/136
- https://github.com/carbon-design-system/carbon-components-react/issues/58
Prettier also took a whack at this, but

fix(childname): use reference to component instead of type.name

---

components/StructuredList.js

fix(StructuredList): title as defaultProps (il8n)

---

.storybook/components/SearchStory.js
components/Search.js

resolves #101 
Mimics native `<input type="search">` close icon. 
Now clicking close icon will invoke `change` event.

fix(Search): clicking bx--search-close icon invokes onChange

---

components/Icon.js

fix(Icon): alt text and description as defaultProps (a11y/il8n)

---

components/CardActionItem.js
components/CardContent.js
components/__tests__/CardContent-test.js

fix(Card): add text strings to defaultProps (Il8n)

---

components/DetailPageHeader.js

fix(DetailPageHeader): add title to defaultProps (il8n)

---

components/FormGroup.js

fix(FormGroup): text strings as defaultProps (il8n)

---

.storybook/components/DatePickerStory.js
.storybook/components/TimePickerStory.js
components/DatePickerInput.js
components/TimePicker.js
components/TimePickerSelect.js

Resolves https://github.com/carbon-design-system/carbon-components-react/issues/93
Added missing labels to Time Picker.

fix(date-picker): fixed a11y violations with date picker and time picker

---

.storybook/components/OrderSummaryStory.js
components/OrderSummary.js
components/__tests__/OrderSummary-test.js
components/__tests__/OrderSummaryCategory-test.js
components/__tests__/OrderSummaryFooter-test.js
components/__tests__/OrderSummaryHeader-test.js
components/__tests__/OrderSummaryList-test.js
components/__tests__/OrderSummaryListItem-test.js
components/__tests__/OrderSummaryTotal-test.js
index.js
yarn.lock

Adds the Order Summary component, still need to add the category functionality / tests, but wanted to get it up so people can get some eyes on it!

feat(order-summary): add simple order summary component

---

components/FileUploader.js
components/__tests__/FileUploader-test.js

fix(FileUploader): add icon descriptions in default props (il8n)

---

components/Tooltip.js
components/TooltipSimple.js

fix(Tooltip): text as defaultProps (il8n)

---

components/SelectItemGroup.js

fix(SelectItemGroup): label as defaultProps (il8n)

---

components/RadioButton.js

fix(RadioButton): labelText as defaultProps (il8n)

---

components/ProgressIndicator.js

fix(ProgressIndicator): label text as defaultProps (il8n)

---

components/OverflowMenuItem.js

fix(OverflowMenu): itemText in defaultProps (il8n)

---

components/Modal.js

fix(Modal): heading and label as defaultProps (il8n)

---

components/Toolbar.js
components/ToolbarSearch.js

fix(Toolbar): text as defaultProps (il8n)

---

components/DetailPageHeader.js

fixes https://github.com/carbon-design-system/carbon-components-react/issues/28

fix(DetailPageHeader): add missing space b/w icon and status

---

package.json

Update the `carbon-icon` range to include v6 as well

fix(icon): stop yarn error about carbon-icon ranges

---

components/FileUploader.js

fixes https://github.com/carbon-design-system/carbon-components-react/issues/146
`FileUploader` can now make use of `enter` and `space` keys to trigger opening `FileUploader`

fix(FileUploader): keyboard accessibility 

---

components/InteriorLeftNavList.js

fix(InteriorLeftNavList): text as defaultProps (il8n)

---

components/Search.js

fix(Search): labelText as defaultProps (il8n)

---

components/Tab.js
components/Tabs.js

related to #107 
Should have two reviewers on this to review refactoring. Basically, I removed the `const props` variable objects that were being spread across the jsx. Changed the props so that they match with how we're declaring them in our other `render` methods across the lib.

fix(Tabs): text strings as defaultProps, other refactoring too (Il8n)

---

package.json

This lets us run both vanilla and react repos at the same time without additional configuration

chore(storybook): swap to port 9000

---

internal/FloatingMenu.js

fix(floatingMenu): wrap usage in if statement

---

package.json
yarn.lock

Add function icons (replaces open-whisk)

chore(build): update to latest carbon-icons

---

components/Tabs.js
components/__tests__/Tabs-test.js

fix(Tabs): update selected state when prop changes

---

components/Pagination.js
components/Slider.js

The props were being passed on the HTML elements which did not support
those attributes
Fixes #179

fix(Pagination/Slider): fix unknownProp warnings

---

.storybook/components/NotificationStory.js
components/Notification.js
components/__tests__/Notification-test.js
index.js

fix(Notification): refactor to not use caption as render conditional

---

components/FileUploader.js

resolves https://github.com/carbon-design-system/carbon-components-react/issues/122
See exact changes in the comments below, all other changes are a result of Prettier.

fix(Filename): various fixes for Filename (used in FileUploader)

---

components/ProgressIndicator.js

fixes https://github.com/carbon-design-system/carbon-components-react/issues/201

fix(ProgressInidicator): remove null rendering

---

components/NumberInput.js
components/__tests__/NumberInput-test.js

fix(NumberInput): set value correctly if min != 0

---

.storybook/components/TileStory.js
components/Tile.js
components/__tests__/Tile-test.js
index.js

Added Tile component.
Consists of
- Tile
- ClickableTile
- SelectableTile
- ExpandableTile
- TileAboveTheFoldContent
- BelowTheFoldContent

feat(tile): added tile component

---

components/Icon.js

Fixes an error message. Probably does lots of good things for performance or whatever. I probably just changed the internet forever.
close #250

fix(Icon): add keys to paths

---

LICENSE
package.json

Closes carbon-design-system/carbon-components-react#193 
**New**
- `LICENSE` file
**Changed**
- License field in `package.json`
**Removed**

chore(license): add LICENSE file and update field in package.json

---

components/Modal.js

- Dry up the ModalBody code a bit
- Use a function for ref as string complains about Owner

fix(Modal): refactor modalBody and refs usage

---

config/jest/cssTransform.js
config/jest/fileTransform.js
config/jest/jsTransform.js
config/jest/setup.js
config/polyfills.js
package.json
setup-jest.js
yarn.lock

Pulled out from #258 so that PR wasn't a monster 😄 
**New**
- `config/jest/**Transform.js`: custom file transformers
- `config/jest/setup.js`: setup hook that pulls in polyfills
- `config/polyfills`: generic polyfills used for products. Pulled from CRA
**Changed**
- `package.json` now has more details Jest config and includes `enzyme-to-json` for snapshots
**Removed**
- `setup-jest.js`

chore(jest): update jest config and setup-related files

---

.storybook/components/DropdownStory.js
components/Dropdown.js

Closes carbon-design-system/carbon-components-react#241 
Carbon Dropdown was not updating its selected value when the property `selectedTest` is passed.
**Changed**
- Dropdown.js
- DropdownStory.js

fix(Dropdown): Update selectedTest when component receives new props

---

components/Slider.js

Added a prop type to slider so user can specify input field type.

User is now allowed to specify type the input box can hold

---

.storybook/components/NotificationStory.js
components/Notification.js
components/__tests__/Notification-test.js

Closes carbon-design-system/carbon-components-react#256
**New**
- Allows an element as the subtitle and or caption for notifications

feat(notifications): support any node for subtitle & caption

---

internal/FloatingMenu.js

Closes carbon-design-system/carbon-components-react#300.
Floating menu has circumvented React's rendering system as the place in DOM goes out of React render tree by nature. React 16 broke such approach by its "circumventing" nature, but introduced an API to officially introduced an API to render to alternate tree - `ReactDOM.createPortal()`. This PR makes use of such new API to fix #300.
**Added**
- Code to clean up `this.menu`, etc. once it's no longer valid
**Changed**
- Moved the main rendering logic from `.renderLayer()` method to regular `.render()` method, in React 16
- Introduced states used in React 16, to trigger `.render()` as positioning info gets available
- Moved `.componentDidMount()` code to `ref` callback to more directly work with the DOM ref

fix(FloatingMenu): support React 16 for floating menu

---

src/index.js

Closes carbon-design-system/carbon-components-react#317
Export ComposedModal component in index.js
**Changed**
- Export ComposedModal component in index.js

fix(ComposedModal): export ComposedModal

---

package.json
src/components/Accordion/Accordion-story.js
src/components/Button/Button-story.js
src/components/Checkbox/Checkbox-story.js
src/components/CodeSnippet/CodeSnippet-story.js
src/components/ContentSwitcher/ContentSwitcher-story.js
src/components/CopyButton/CopyButton-story.js
src/components/DatePicker/DatePicker-story.js
src/components/DetailPageHeader/DetailPageHeader-story.js
src/components/Footer/Footer-story.js
src/components/Form/Form-story.js
src/components/Modal/Modal-story.js
src/components/ModalWrapper/ModalWrapper-story.js
src/components/Notification/Notification-story.js
src/components/NumberInput/NumberInput-story.js
src/components/OverflowMenu/OverflowMenu-story.js
src/components/RadioButton/RadioButton-story.js
src/components/RadioButtonGroup/RadioButtonGroup-story.js
src/components/Search/Search-story.js
src/components/Select/Select-story.js
src/components/Slider/Slider-story.js
src/components/Tabs/Tabs-story.js
src/components/TextArea/Textarea-story.js
src/components/TextInput/TextInput-story.js
src/components/Toggle/Toggle-story.js
src/components/Toolbar/Toolbar-story.js

The actions addon from react is deprecated. Its a standalone module now
Fixes: #325

fix(Storybook): use actions from module

---

src/components/TimePicker/TimePicker-test.js
src/components/TimePicker/TimePicker.js

Closes carbon-design-system/carbon-components-react #335
Added a new prop 'value' in TimePicker Component to set the value programmatically.
Change log
**Changed**
- Added new Prop value, to set the value programmatically
- Updated tests

fix: Added a new prop 'value' in TimePicker Component .

---

src/components/Accordion/Accordion-story.js
src/components/Breadcrumb/Breadcrumb-story.js
src/components/Button/Button-story.js
src/components/Checkbox/Checkbox-story.js
src/components/DatePicker/DatePicker-story.js
src/components/Dropdown/Dropdown-story.js
src/components/Form/Form-story.js
src/components/Link/Link-story.js
src/components/Modal/Modal-story.js
src/components/ModalWrapper/ModalWrapper-story.js
src/components/Notification/Notification-story.js
src/components/NumberInput/NumberInput-story.js
src/components/OverflowMenu/OverflowMenu-story.js
src/components/ProgressIndicator/ProgressIndicator-story.js
src/components/RadioButtonGroup/RadioButtonGroup-story.js
src/components/Search/Search-story.js
src/components/Select/Select-story.js
src/components/Slider/Slider-story.js
src/components/StructuredList/StructuredList-story.js
src/components/Tabs/Tabs-story.js
src/components/TextArea/Textarea-story.js
src/components/TextInput/TextInput-story.js
src/components/Tooltip/Tooltip-story.js
src/components/TooltipSimple/TooltipSimple-story.js

Closes [#380 ](https://github.ibm.com/Bluemix/carbon-issues/issues/380)(internal).
Updated content in components to be consistent across Design Kit, Carbon website, and Carbon Components. 
**Changed**
- Content in all components. 
**Removed**
- Sentence casing from labels.

chore: Updating content in components

---

.cfignore
Staticfile
manifest.yml

Fixes deployment issues from last merge (forgot to add in Staticfile for the `root` config)

chore: add staticfile and cfignore for deploys

---

src/components/ModalWrapper/ModalWrapper.js

Fixes https://github.com/carbon-design-system/carbon-components-react/issues/398
Adds `disabled` prop to `ModalWrapper`

fix(modal): enable button disable

---

src/components/FormItem/FormItem-test.js
src/components/FormItem/index.js
src/components/FormLabel/FormLabel-test.js
src/index.js

The export for formItem was not set correctly.
Updated the tests to use the exported module instead of the file directly

fix(FormItem): use correct export

---

.prettierignore
package.json

npm (or yarn, not sure which), auto-formats the package.json file. These are the changes it wants.

chore(Pkg): add npm autoformatting

---

src/components/DatePicker/DatePicker-story.js
src/components/DatePicker/DatePicker.js

Closes carbon-design-system/carbon-components-react#286
Fixing up date picker.
#

fix(datePicker): Send arguments to datepicker on change event

---

package.json
src/components/Checkbox/Checkbox-story.js
src/components/Checkbox/Checkbox-test.js
src/components/Checkbox/Checkbox.js
src/components/MultiSelect/MultiSelect.js
yarn.lock

Adds indeterminate checkbox 
resolves #448

feat: Indeterminate checkbox

---

src/components/DataTableData/DataTableData.js

fix(data-table): Update checkbox html

---

package.json
yarn.lock

Remove `shelljs` devDependency
**New**
- {{new thing}}
**Changed**
- {{change thing}}
**Removed**
- remove `shelljs` devDependency

chore: remove shelljs devDependency

---

package.json
src/components/DropdownV2/DropdownV2-story.js
src/components/DropdownV2/DropdownV2-test.js
src/components/DropdownV2/DropdownV2.js
src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap
src/components/DropdownV2/index.js
src/components/ListBox/ListBoxMenuIcon.js
src/components/ListBox/__tests__/__snapshots__/ListBoxMenuIcon-test.js.snap
src/components/ListBox/test-helpers.js
yarn.lock

Adds in Dropdown v2 to the project 😄 
**New**
- `DropdownV2` component
**Changed**
- New `assertMenuClosed` helper for `ListBox`
- Added `alt` tag for `ListBoxMenuIcon`
**Removed**

feat: add dropdown v2

---

package.json
src/components/ComboBox/ComboBox.js
src/components/DatePicker/DatePicker.js
src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap
src/components/ListBox/__tests__/__snapshots__/ListBoxField-test.js.snap
src/components/ListBox/__tests__/__snapshots__/ListBoxMenuIcon-test.js.snap
src/components/ListBox/__tests__/__snapshots__/ListBoxSelection-test.js.snap
src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap
yarn.lock

Updated the version of `carbon-components` to fix the alignment of the checkboxes in the tables.

fix(components): updated carbon components to fix checkboxes

---

src/components/OverflowMenu/OverflowMenu.js

Refs #420.
**Changed**
- Hoisted the code to generate menu options nodes.

chore(OverflowMenu): hoist menu options nodes

---

src/components/Tooltip/Tooltip.js

Fixes #479.
**New**
- Virtual parent/child relationship for a11y for floating menu.

fix(Tooltip): let screen reader read tooltip content

---

src/index.js

Adds ListBox variants to the default export
**New**
**Changed**
- `src/index.js` now includes:
- DropdownV2
- MultiSelect
- ComboBox
**Removed**

feat: add list box variants to default export

---

src/components/DatePicker/DatePicker.js

**Changed**
- Args of `removeEventListener()` call in `cWU` of `DatePicker`.

fix(DatePicker): fix JS error when it's being unmounted

---

README.md

**New**
- N/A
**Changed**
- Updated port number in README.md for accessing storybook.
**Removed**
- N/A

fix: updated port number for accessing storybook

---

src/index.js

Added `PaginationV2` to the default export list `index.js`.

fix(pagination): added paginationv2 to export list

---

src/components/InteriorLeftNavItem/InteriorLeftNavItem.js

**New**
- Import of `window-or-global` for `<InteriorLeftNavItem>`

fix(InteriorLeftNavItem): fix location object ref in render logic

---

package.json
src/components/Icon/Icon.js
src/components/MultiSelect/tools/sorting.js
src/components/TableBody/TableBody.js
src/tools/array.js

**New**
- ESLint rule for check for JSDoc comments.

chore(lint): lint JSDoc comments

---

src/components/InteriorLeftNavList/InteriorLeftNavList.js

**New**
- N/A
**Changed**
- Addressed #505 by adding aria-label attribute to ul element within the InteriorLeftNavList component.
**Removed**
- N/A

fix: resolves #505 by adding aria-label to ul component

---

src/components/OverflowMenu/OverflowMenu.js
yarn.lock

Closes #579 
Changed from `onClick` back to `closeMenu`.

fix(overflow-menu): switched prop back to closeMenu

---

package.json
src/components/ToggleSmall/ToggleSmall-story.js
src/components/ToggleSmall/ToggleSmall-test.js
src/components/ToggleSmall/ToggleSmall.js
src/components/ToggleSmall/index.js
yarn.lock

https://github.ibm.com/Bluemix/carbon-issues/issues/453
**New**
Small Toggle Component

feat(SmallToggle): Add small toggle component

---

src/index.js

Adds in `export` for `ToggleSmall`

fix(toggle): add correct export for toggle small

---

package.json
yarn.lock

Adds `invariant` to dependencies. Seems like it might have been omitted due to a bad merge, or just forgetfulness on my part 🙃 
**New**
**Changed**
- `invariant` is now accurately listed as a dependency
**Removed**

fix(package): add invariant to deps

---

src/components/ComboBox/ComboBox.js

Closes #603 
Added `aria-label` prop to the input field in the `ComboBox`.
**Changed**
* `ComboBox.js`

fix(combo-box): added aria-label to input field

---

.travis.yml

Updates Yarn to v1.5.1 in CI
**New**
**Changed**
* `.travis.yml` now downloads Yarn v1.5.1
**Removed**

chore(package): update yarn

---

README.md

Fixes #689.
**New**
* {{new thing}}
**Changed**
* {{change thing}}
**Removed**
* {{removed thing}}

Fix typo in Yarn install command

---

src/components/Slider/Slider.js

Closes #621 
- Switched the id from the `input` to the `div` with the slider role
- Added `aria-label` to the number input
**Changed**
* `Slider.js`

fix(slider): fixed a11y errors

---

.storybook/polyfills.js

Update polyfill list to include `Object#values`.
**New**
**Changed**
* `.storybook/polyfills` now includes a polyfill for `Object#values`
**Removed**

chore(polyfill): update polyfill list

---

src/components/Icon/Icon.js

Rename 'name' ---> 'icon' for better readability
**New**
* nothing
**Changed**
* the name of a variable in Icon
**Removed**
* nothing

Rename 'name' ---> 'icon' for better readability

---

src/components/DropdownV2/DropdownV2-story.js
src/components/DropdownV2/DropdownV2.js

In the case that the selected item is driven by an external component.
**New**
* new `selectedItem` prop on DropdownV2 to support uncontrolled behaviours

feat(dropdownv2): Support uncontrolled props

---

src/components/Modal/Modal.js

**New**
**Changed**
- Change `ariaLabel` to `aria-label` in `Modal`
**Removed**

fix(Modal): change ariaLabel to aria-label

---

src/components/FileUploader/FileUploader.js

Closes  #610
move tabIndex props from div to the label element, 
and no weird focus 
**New**
**Changed**
**Removed**

fix(FileUploader): fix the weird focus, resolves #610

---

src/components/Tooltip/Tooltip.js

Fixes #876.
**New**
* Added missing prop dirty-check in `<Tooltip>`’s `cWRP` code.

fix(Tooltip): fix missing dirty-check in cWRP

---

src/components/DropdownV2/DropdownV2-story.js
src/components/DropdownV2/DropdownV2-test.js
src/components/DropdownV2/DropdownV2.js
src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap
src/components/MultiSelect/FilterableMultiSelect.js
src/components/MultiSelect/MultiSelect-story.js
src/components/MultiSelect/MultiSelect.js
src/components/MultiSelect/__tests__/__snapshots__/FilterableMultiSelect-test.js.snap

Ref https://github.ibm.com/carbon/issues/issues/736
Add light variation for dropdown and multiselect
*need styles from PR https://github.com/carbon-design-system/carbon-components/pull/809 to view

feat: Light dropdown & multiselect

---

.storybook/.babelrc
config/jest/jsTransform.js
package.json
src/components/DataTable/TableToolbarSearch.js
src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/components/DataTable/__tests__/__snapshots__/TableToolbarSearch-test.js.snap
src/components/DatePicker/DatePicker-story.js
src/components/DatePicker/DatePicker-test.js
src/components/DatePicker/DatePicker.js
src/components/OverflowMenu/OverflowMenu.js
src/components/Pagination/Pagination-test.js
src/components/Pagination/Pagination.js
src/components/PaginationV2/PaginationV2-test.js
src/components/PaginationV2/PaginationV2.js
src/components/Search/Search-story.js
src/components/Search/Search.js
src/components/SearchFilterButton/SearchFilterButton.js
src/components/Slider/Slider-story.js
src/components/Slider/Slider-test.js
src/components/Slider/Slider.js
src/components/Tooltip/Tooltip.js
src/index.js
yarn.lock

feat(slider): Light variation

---

src/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/components/DataTable/__tests__/__snapshots__/TableToolbarSearch-test.js.snap
src/components/Search/Search-test.js
src/components/Search/Search.js

chore(search): remove icons

---

package.json
src/components/DatePickerInput/DatePickerInput.js
src/components/NumberInput/NumberInput-test.js
src/components/NumberInput/NumberInput.js
src/components/TextArea/TextArea.js
src/components/TextInput/TextInput.js
src/components/TimePicker/TimePicker.js
yarn.lock

- Fixed the order of some of the input elements to make sure that the labels change color on focus
- Fixed an issue with the NumberInput arrow sizes
**Changed**
* Fixed the order of the label and the input on TextInput, TextArea, DatePicker, TimePicker, NumberInput
* Fixed a bug with the arrow sizes on NumberInput

fix(components): fixed some issues with the inputs

---

src/components/ProgressIndicator/ProgressIndicator.js

Removes warning about `fill-rule` being `fillRule`

fix(progress-indicator): fix svg warning

---

src/index.js

Add in exports for the new `TooltipIcon` and `TooltipDefinition`

fix(export): add tooltip exports

---

src/components/Tag/Tag-story.js
src/components/Tag/Tag-test.js
src/components/Tag/Tag.Skeleton.js
src/components/Tag/Tag.js
src/components/Tag/index.js

Closes https://github.com/carbon-design-system/carbon-components-react/issues/1046
Refs https://github.com/carbon-design-system/carbon-addons-cloud-react/issues/14
Adds `Tag` back into the repo
**New**
* `Tag`

feat(tag): add tag back in

---

package.json
yarn.lock

Update to 5.2.1 instead as this does not break anything from the original PR (#985 )

Greenkeeper/all contributors cli 5.2.1

---

package.json
yarn.lock

Points the `git` URL to the new `IBM` address

fix(package): point to new IBM url

---

.all-contributorsrc
.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
package.json
src/components/Search/Search-story.js

More work to sync with project move.
**Changed**
* Several refs from `carbon-design-system` org to `IBM` org.

chore: sync with project move

---

src/components/CodeSnippet/CodeSnippet.js
yarn.lock

Add the functionality to provide a custom description for copy button when using code-snippet. Example usecase is localization, Instead of having `Copy to clipboard` hard coded developer should be allowed to provide the value from locales.
**New**
* Provide a custom description for copy button when using code-snippet
**Changed**
* Provide `iconDescription` to `CopyButton` when calling it from `CodeSnippet` component
**How the flow will change?**
- Storybook snippet: http://recordit.co/jiiQ1w5uLE

feat(codeSnippet): add an option to provide copy button description

---

src/components/DropdownV2/DropdownV2.js

fix #1099
**New**
* {{new thing}}
**Changed**
* {{change thing}}
**Removed**
* {{removed thing}}

fix(DropdownV2): add ID prop

---

src/internal/FloatingMenu.js

Fixes #605.
**New**
* `scrollX` support in floating menu.

feat(FloatingMenu): add horizontal scrolling support

---

src/components/CodeSnippet/CodeSnippet.js

Resolves https://github.com/IBM/carbon-components-react/issues/1141

fix(codesnippet): set shouldShowMoreLessBtn if children change

---

src/components/AccordionItem/AccordionItem.js
src/components/RadioTile/RadioTile.js
src/components/SearchFilterButton/SearchFilterButton.js
src/components/SearchLayoutButton/SearchLayoutButton.js
src/components/TableData/TableData.js
src/components/TableHeader/TableHeader.js
src/components/Tile/Tile.js
src/components/ToolbarSearch/ToolbarSearch.js

Fixes #1147.
**New**
* `iconDescription` prop for several components.

fix(Icon): make icon descriptions configurable

---

src/components/AccordionItem/AccordionItem-test.js
src/components/AccordionItem/AccordionItem.js
src/components/ComposedModal/ComposedModal-test.js
src/components/ComposedModal/ComposedModal.js
src/components/ContentSwitcher/ContentSwitcher-test.js
src/components/ContentSwitcher/ContentSwitcher.js
src/components/FileUploader/FileUploader-test.js
src/components/FileUploader/FileUploader.js
src/components/NumberInput/NumberInput-test.js
src/components/NumberInput/NumberInput.js
src/components/OverflowMenu/OverflowMenu-test.js
src/components/OverflowMenu/OverflowMenu.js
src/components/PaginationV2/PaginationV2-test.js
src/components/PaginationV2/PaginationV2.js
src/components/ProgressIndicator/ProgressIndicator-test.js
src/components/ProgressIndicator/ProgressIndicator.js
src/components/RadioButtonGroup/RadioButtonGroup-test.js
src/components/RadioButtonGroup/RadioButtonGroup.js
src/components/SearchLayoutButton/SearchLayoutButton-test.js
src/components/SearchLayoutButton/SearchLayoutButton.js
src/components/Tabs/Tabs-test.js
src/components/Tabs/Tabs.js
src/components/Tile/Tile-test.js
src/components/Tile/Tile.js
src/components/TileGroup/TileGroup-test.js
src/components/TileGroup/TileGroup.js
src/components/TimePicker/TimePicker-test.js
src/components/TimePicker/TimePicker.js
src/components/Tooltip/Tooltip-test.js
src/components/Tooltip/Tooltip.js

This PR makes a switch from `cWRP` -> `gDSFP` for basic components.
**Changed**
* Switch from `cWRP` to `gDSFP`.

chore(components): cWRP -> gDSFP migration for basic components

---

src/components/ComboBox/ComboBox.js

Closes IBM/carbon-components-react#1270
Update `ComboBox` to pass along `translateWithId` to `ListBoxSelection`
**Changed**
* Update `ComboBox` to pass along `translateWithId` to `ListBoxSelection`

feat(ComboBox): clear icon translateWithId support

---

src/components/DatePicker/DatePicker.js

Closes https://github.com/IBM/carbon-components-react/issues/1331
Checks to ensure element exists before adding/removing event listeners
**New**
- Null checks on `this.inputField`

fix(date-picker): check if input field is null

---

src/internal/FloatingMenu.js

Fixes #1349.
**Changed**
* Changed the timing of floating menu position calculation, from `cDM()` to the actual timing of floating menu body being mounted, given they can be different in SSR scenario.

fix(FloatingMenu): cope with SSR

---

.travis.yml

Update Yarn version in TravisCI
**New**
**Changed**
* Yarn version changed to 1.10.1
**Removed**

chore(ci): update Yarn version

---

src/components/ProgressIndicator/ProgressIndicator.js

Closes IBM/carbon-components-react#1433
Corrected a PropType on ProgressStep Component
**Changed**
* Corrected label PropType from string to node

chore: Corrected label PropType from string to node, resolves #1433

---

src/components/PaginationV2/PaginationV2.js

https://github.com/IBM/carbon-components-react/issues/1473
Fix the accessibility issue.
**New**
* aria-label={backwardText}
* aria-label={forwardText}

Fix accessibility issue for #1473

---

src/components/ComboBox/ComboBox.js

Fixes #1187.
**New**
* A mechanism to `<ComboBox>` to propagate misc props to the `<input>` in it.

feat(ComboBox): propagate misc props to input

---

src/components/NumberInput/NumberInput-story.js
src/components/NumberInput/NumberInput-test.js
src/components/NumberInput/NumberInput.js

Closes IBM/carbon-components-react#1509
Add hideLabel prop to NumberInput component.
**NumberInput**
* add hideLabel prop

feat(NumberInput): optionally hide the label, resolves #1509

---

src/components/TextArea/TextArea.js

Closes #1529 
Support screenreading TextArea invalid text.
**New**
* Support screenreading invalid text

fix(TextArea): support screenreading invalid text, resolves #1529

---

package.json
src/components/Tag/Tag-story.js
src/components/Tag/Tag.js

Closes IBM/carbon-components-react#1518
This PR will add the experimental Tag component
**New**
* experimental `<Tag>`
* `start:experimental` NPM script for local development with experimental components

feat(Tag): add experimental tag component

---

src/components/StructuredList/StructuredList-story.js

Closes IBM/carbon-components-react#1481
Add flag to allow experimental structured list
**Changed**
* conditionally render experimental component based on feature flag

feat(StructuredList): add experimental structured list

---

src/components/Search/Search-story.js

Closes IBM/carbon-components-react#1543
Just a default value for Search component story to make it less confusing.
**New**
* Default value

fix(Search): provide a default value

---

src/components/UIShell/HeaderMenuButton.js
src/components/UIShell/__tests__/__snapshots__/HeaderMenuButton-test.js.snap

Update HeaderMenuButton to use Menu20
**New**
**Changed**
* Update HeaderMenuButton to use Menu20
**Removed**

fix(ui-shell): update HeaderMenuButton to use Menu20

---

src/components/ComposedModal/ComposedModal-story.js
src/components/ComposedModal/ComposedModal-test.js
src/components/ComposedModal/ComposedModal.js

Closes IBM/carbon-components-react#1599
This PR adds support for the `danger` prop on `<ComposedModal>`
**New**
- Add `danger` prop

feat(ComposedModal): add `danger` prop

---

src/components/FileUploader/FileUploader.js

Closes IBM/carbon-components-react#1644
This PR will add the new experimental file uploader changes

feat(FileUploader): add experimental FileUploader

---

package.json
src/components/ComposedModal/ComposedModal.js
src/components/Modal/Modal-test.js
src/components/Modal/Modal.js
src/components/ModalWrapper/__snapshots__/ModalWrapper-test.js.snap

Closes IBM/carbon-components-react#1649
This PR will add the new experimental modal and experimental composed modal changes

feat(Modal): add experimental modal

---

src/components/Button/Button-story.js
src/components/Button/Button.js

Closes IBM/carbon-components-react#1668
This PR will add the new experimental button changes

feat(Button): add experimental button

---

src/components/RadioTile/RadioTile.js
src/components/Tile/Tile-story.js
src/components/Tile/Tile.js

Closes IBM/carbon-components-react#1688
Closes #1689
Closes #1690
This PR will add the new experimental tile changes, as well as keyboard navigation support and visual bugfixes

feat(Tile): add experimental tile

---

package.json
src/components/Select/Select.js

Closes IBM/carbon-components-react#1676
This PR will add the new experimental select changes

feat(Select): add support for experimental styles

---

package.json
src/components/Search/Search.js

Closes IBM/carbon-components-react#1728
This PR will add the experimental search component
Related: https://github.com/IBM/carbon-components/pull/1617

feat(search): add experimental search component

---

src/components/ComboBox/ComboBox.js
src/components/ListBox/ListBoxMenuIcon.js
src/components/ListBox/ListBoxSelection.js

Closes IBM/carbon-components-react#1712
This PR adds experimental icons for the ComboBox and ListBox components
depends on https://github.com/IBM/carbon-components/pull/1599 for some styling

feat(ComboBox): add experimental ComboBox

---

src/components/DropdownV2/DropdownV2-story.js
src/components/DropdownV2/DropdownV2-test.js
src/components/DropdownV2/DropdownV2.js
src/components/DropdownV2/__snapshots__/DropdownV2-test.js.snap

this is a v5 version of https://github.com/IBM/carbon-components-react/pull/1608, the functionality doesn't depend on anything v6-specific so it would be nice to port back.

feat(DropdownV2): allows consumers to specify render prop for dropdown items

---

src/components/NumberInput/NumberInput-story.js
src/components/NumberInput/NumberInput.js

Closes IBM/carbon-components-react#1658
This PR adds `aria-live` and `aria-atomic` attributes to improve a11y

fix(NumberInput): add aria attributes for a11y

---

src/components/DataTable/DataTable-story.js
src/components/DataTable/stories/with-boolean-column.js
src/components/DataTable/tools/filter.js

For issue #1811 
Skip the search filter for columns with boolean value on DataTable.
Also added a story for this. I can remove it if it's not necessary.
**New**
- src/components/DataTable/stories/with-boolean-column.js
**Changed**
- src/components/DataTable/tools/filter.js
- src/components/DataTable/DataTable-story.js
**Removed**
- {{removed thing}}

fix: (DataTable): filter without boolean column"

---

.github/ISSUE_TEMPLATE/accessibility-issue--.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md

https://github.com/stackriot/carbon-components-react/pull/205
Needed to be prettified.

fix: run prettier to fix issues with new md docs

---

src/components/DropdownV2/DropdownV2.js

Selected item is highlighted with Combobox but not with DropdownV2
**Changed**
- selected item is also highlighted in the list box when open

feat(DropdownV2): highlight selected item in drop down

---

src/components/DataTable/TableSelectAll.js
src/components/DataTable/TableSelectRow.js
src/components/DataTable/__tests__/TableSelectAll-test.js
src/components/DataTable/__tests__/TableSelectRow-test.js
src/components/DataTable/__tests__/__snapshots__/TableSelectAll-test.js.snap
src/components/DataTable/__tests__/__snapshots__/TableSelectRow-test.js.snap

feat(DataTable): custom classes support for TableSelectAll and TableSelectRow

---

src/components/Tag/Tag-story.js
src/components/Tag/Tag.js

**Removed**
- removed `basic` class name and set `red` as default color tag shown

chore(tag): fix class name

---

src/components/Pagination/Pagination-story.js

after removing deprecated old pagination, we needed to add story for the new one!

add story for pagination

---

docs/migration/migrate-to-7.x.md

Remove unreleased block from migration docs.
**New**
**Changed**
- Remove unreleased block from migration docs
**Removed**

docs(migration): remove unreleased block

---

examples/codesandbox/package.json
examples/codesandbox/yarn.lock

Closes IBM/carbon-components-react#2185

docs: update codepen example

---

scripts/build.js

Closes IBM/carbon-components-react#2201

fix: delete correct build folders

---

src/components/DataTableSkeleton/DataTableSkeleton-test.js
src/components/DataTableSkeleton/DataTableSkeleton.js

fix(DataTableSkeleton): use new classnames

---

src/components/Switch/Switch.js

Match HTML change from https://github.com/IBM/carbon-components/pull/2290
**Changed**
- src/components/Switch/Switch.js

fix: match vaniila 2290

---

package.json

Remove un-used boswer dependency.
**New**
**Changed**
- `bowser` dependency is no longer in `package.json`
**Removed**

chore(package): remove bowser dependency

---

src/components/UIShell/Link.js
src/components/UIShell/SideNavMenu.js

- Use new PropTypes.elementType to allow for `Link` from third party libraries
- Make menu icons optional

feat: update SideNav and Menu

---

README.md

chore(readme): fix broken ci status badge photo

---

package.json

Create release commit for `v6.114.1` (the last commit for v6 was [`v6.114.0`](https://www.npmjs.com/package/carbon-components-react/v/6.114.0))
**New**
**Changed**
- Version updated to `v6.114.1`
**Removed**

chore(release): v6.114.1

---

src/components/StructuredList/StructuredList-story.js

**Changed**
- remove stray commas in `StructuredList` story

fix(structured-list): remove stray commas in story

---

package.json

chore(release): v6.115.4

---

src/components/NumberInput/NumberInput.js

Ports over fix from https://github.com/carbon-design-system/carbon/pull/3662/files
Refs https://github.com/carbon-design-system/carbon/issues/3645

fix(number-input): mimic text input validation a11y

---

src/components/ComboBox/ComboBox-test.js
src/components/ComboBox/ComboBox.js

Support render custom element for an item in ComboBox in v6.

fix(ComboBox): support itemToElement

---

package.json

chore(release): v6.116.1
